function audit=validate_v21_outputs(v21Root)
%VALIDATE_V21_OUTPUTS Fail fast if a mandatory v2.1 artifact is absent/empty.

if nargin<1, v21Root=fileparts(fileparts(mfilename("fullpath"))); end
tables=["table_sampling_geometry_v21.csv","table_edge_bias_variance_v21.csv", ...
    "table_C_information_v21.csv","table_measurement_reuse_v21.csv", ...
    "table_NIS_NEES_v21.csv","table_adc_afe_joint_v21.csv", ...
    "table_modelB_edge_features_v21.csv","table_modelAP_vs_B_v21.csv", ...
    "table_timing_boundary_v21.csv","table_CRLB_v21.csv", ...
    "table_blind_validation_v21.csv","result_metrics_v21.csv"];
figures="fig_v21_"+compose("%02d",1:15)+[ ...
    "_sampling_feasible_region","_phase_point_availability", ...
    "_edge_bias_variance","_predicted_vs_actual_esr_sigma", ...
    "_C_information_vs_load_duty","_double_counting_effect", ...
    "_NIS_NEES_consistency","_CI_coverage","_adc_afe_pass_region", ...
    "_alias_error_correlation","_modelAP_modelB_edge_overlay", ...
    "_modelAP_modelB_error","_timing_pass_probability", ...
    "_empirical_vs_CRLB","_final_design_region"]+".png";
reports=["THEORY_CLOSURE_V21.md","SAMPLING_FEASIBILITY_V21.md", ...
    "PARASITIC_MODEL_RECONCILIATION.md","ESTIMATOR_FORMULATION_AUDIT.md", ...
    "RESULT_V21_FOR_CHATGPT.md","V2_V21_COMPARISON.md","README_V21.md"];
missing=string.empty(0,1); empty=missing;
for name=tables
    path=fullfile(v21Root,"results","tables",name);
    if ~isfile(path), missing(end+1)=path; elseif dir(path).bytes==0, empty(end+1)=path; end %#ok<AGROW>
end
for name=figures
    path=fullfile(v21Root,"results","figures",name);
    if ~isfile(path), missing(end+1)=path; elseif dir(path).bytes==0, empty(end+1)=path; end %#ok<AGROW>
end
for name=reports
    path=fullfile(v21Root,name);
    if ~isfile(path), missing(end+1)=path; elseif dir(path).bytes==0, empty(end+1)=path; end %#ok<AGROW>
end
assert(isempty(missing),"v21:MissingArtifacts","Missing: %s",strjoin(missing,", "));
assert(isempty(empty),"v21:EmptyArtifacts","Empty: %s",strjoin(empty,", "));
geometry=readtable(fullfile(v21Root,"results","tables",tables(1)));
assert(height(geometry)==5544,"Unexpected sampling geometry row count.");
stats=readtable(fullfile(v21Root,"results","tables","table_NIS_NEES_seed_level_v21.csv"));
assert(height(stats)==600,"Expected 600 seed-level statistical rows.");
audit=struct("tableCount",numel(tables),"figureCount",numel(figures), ...
    "reportCount",numel(reports),"geometryRows",height(geometry), ...
    "seedRows",height(stats),"passed",true);
fprintf("v2.1 audit PASS: %d tables, %d figures, %d reports.\n", ...
    audit.tableCount,audit.figureCount,audit.reportCount);
end
