function cfg = v22_default_config()
%V22_DEFAULT_CONFIG Locked assumptions for the native-ADC feasibility study.
%   Reference ADC modes are parameterized because the repository does not
%   identify a target DSP part number. They are not device specifications.

cfg = struct;
cfg.version = "v2.2";
cfg.targetStatus = "TARGET_DSP_NOT_FIXED";
cfg.fswHz = 50e3;
cfg.Ts = 1 / cfg.fswHz;
cfg.C0 = 100e-6;
cfg.ESR0 = 50e-3;
cfg.CFactors = [.8 .9 1.0];
cfg.ESRFactors = [1 1.5 2];
cfg.cycles = [1 4 16 64 256 1024];
cfg.adcRatesHz = 1e6 * [1 1.1 1.6 2 3 3.5 4 5];
cfg.guardsUs = [.2 .5 .8 1.0];
cfg.windowsUs = [1.5 2 2.5 3 4 5];
cfg.pointsPerSide = [3 4 5 6 8];
cfg.phaseResidualNs = 50;
cfg.currentMargins = [1.25 1.5 2.0];
cfg.standardCurrentRangesA = [5 10 15 20 25 30 40];
cfg.currentRangeA = 20;
cfg.analogNoiseSweepmV = [.25 .5 1 2 5 10];
cfg.enobSweep12 = [9.5 10 10.5 11 11.5 12];
cfg.mcSeeds = 32;
cfg.blindSeeds = 40;
cfg.primaryCycles = 1024;
cfg.primaryNoiseCase = "Q3_full_nonideal";
cfg.primaryCalibration = "Cal3";
cfg.primaryFusion = "TS_SLTVKE_sequential";
cfg.edgeTimingSensitivity = .05;
cfg.kRCalibrationResidual = .0025;
cfg.modelBESLH = 20e-9;
cfg.modelBDurationS = .0025;

cfg.operatingCases = struct( ...
    "name", {"low_CCM_margin", "nominal", "high_load", "high_D"}, ...
    "Vin", {24, 24, 24, 24}, ...
    "D", {.40, .40, .40, .65}, ...
    "Rload", {30, 10, 5, 7.5}, ...
    "loadLabel", {"low_CCM", "nominal", "high", "high_D"});

common = struct("inputReferenceV", 3.3, "inputRangeV", "0 to 3.3", ...
    "singleEndedDifferential", "DATASHEET_NOT_SPECIFIED", ...
    "socCount", "DATASHEET_NOT_SPECIFIED", ...
    "pwmTrigger", "PARAMETERIZED_REQUIRED", ...
    "simultaneousConversion", "PARAMETERIZED_REQUIRED", ...
    "acquisitionWindow", "DATASHEET_NOT_SPECIFIED", ...
    "conversionLatency", "DATASHEET_NOT_SPECIFIED", ...
    "inl", "PARAMETER_SWEEP", "dnl", "PARAMETER_SWEEP", ...
    "snrSinad", "DATASHEET_NOT_SPECIFIED", ...
    "offsetError", "PARAMETER_SWEEP", "gainError", "PARAMETER_SWEEP", ...
    "referenceRequirement", "External low-noise reference sensitivity", ...
    "channelSkew", "PARAMETER_SWEEP");
p1 = complete_profile(common, "native_12bit_highspeed", ...
    "native_reference", 12, 4e6, 10.5, 4, "12-bit high-speed reference mode");
p2 = complete_profile(common, "native_16bit_slow", ...
    "native_reference", 16, 1.1e6, 13.5, 2, "16-bit slow reference mode");
p3 = complete_profile(common, "external_14bit_reference", ...
    "external_control", 14, 5e6, 12.0, 4, "14-bit external control");
p4 = complete_profile(common, "external_16bit_reference", ...
    "external_control", 16, 5e6, 13.5, 4, "16-bit external control");
cfg.profiles = [p1 p2 p3 p4];

cfg.architectures = struct( ...
    "id", {"V1", "V2", "V3"}, ...
    "name", {"wide_range_vT", "dual_range_Vabs_Vedge", ...
        "level_shifted_precision_window"}, ...
    "cLowV", {0, 0, 30}, "cHighV", {100, 80, 75}, ...
    "rLowV", {0, -2, 30}, "rHighV", {100, 2, 75}, ...
    "separateEdgeChannel", {false, true, false}, ...
    "highpassHz", {0, 5e3, 0}, "lowpassHz", {1.2e6, 1.2e6, 1.2e6}, ...
    "nominalKR", {.92, .96, .94}, ...
    "description", { ...
        "Single 0-100 V absolute terminal-voltage channel", ...
        "0-80 V Vabs plus AC/level-shifted -2 to +2 V Vedge", ...
        "Single 30-75 V protected precision window"});

cfg.calibrations = struct( ...
    "name", {"Cal0", "Cal1", "Cal2", "Cal3"}, ...
    "offsetResidualLsb", {2.0, .10, .10, .10}, ...
    "gainResidualFraction", {.005, .0005, .0005, .0005}, ...
    "timingResidualNs", {120, 120, 20, 20}, ...
    "kRCorrected", {false, false, false, true}, ...
    "settlingResidualFraction", {.004, .002, .001, .0005}, ...
    "systematicFloorC", {.05, .025, .020, .012}, ...
    "systematicFloorR", {.10, .060, .040, .012});
end

function profile = complete_profile(profile, name, type, bits, fsHz, enob, ...
        modules, note)
profile.name = name;
profile.type = type;
profile.bits = bits;
profile.fsHz = fsHz;
profile.enob = enob;
profile.moduleCount = modules;
profile.resolutionMode = note;
profile.partNumber = "NOT_FIXED";
profile.dataSource = "PARAMETERIZED_REFERENCE_NOT_DATASHEET";
profile.inlLsb = 1.5;
profile.dnlLsb = .75;
end
