function assemble_gpt_review_package(packageRoot, repositoryRoot)
%ASSEMBLE_GPT_REVIEW_PACKAGE Copy the auditable paper-selection evidence.
reviewRoot = fullfile(packageRoot, "gpt_review_package");
folders = [reviewRoot, fullfile(reviewRoot, "tables"), ...
    fullfile(reviewRoot, "figures"), fullfile(reviewRoot, "raw"), ...
    fullfile(reviewRoot, "logs"), fullfile(reviewRoot, "docs")];
for folder = folders
    if ~isfolder(folder)
        mkdir(folder);
    end
end

rootFiles = ["README.md", "ALGORITHM_SELECTION_PROTOCOL.md", ...
    "LOCKED_ALGORITHM_SELECTION_HYPERPARAMETERS.csv", ...
    "SOURCE_MODEL_MANIFEST.csv", "FINAL_ESTIMATOR_DECISION.md", ...
    "PAPER_METHOD_COMPARISON.md", "PAPER_DYNAMIC_RESULTS.md", ...
    "PAPER_READY_ALGORITHM_SELECTION.md", ...
    "result_metrics_algorithm_selection_v1.csv"];
for name = rootFiles
    copyfile(fullfile(packageRoot, name), fullfile(reviewRoot, name), "f");
end
copyfile(fullfile(packageRoot, "results", "tables", ...
    "table_algorithm_*.csv"), fullfile(reviewRoot, "tables"), "f");
copyfile(fullfile(packageRoot, "results", "figures", "fig_alg_*.png"), ...
    fullfile(reviewRoot, "figures"), "f");
copyfile(fullfile(packageRoot, "results", "raw", ...
    "algorithm_selection_consolidated_trace.csv"), ...
    fullfile(reviewRoot, "raw"), "f");
copyfile(fullfile(packageRoot, "logs", ...
    "audit_paper_algorithm_selection_v1.txt"), ...
    fullfile(reviewRoot, "logs"), "f");
copyfile(fullfile(repositoryRoot, "docs", ...
    "Codex_Cuk_Paper_Algorithm_Selection_v1.md"), ...
    fullfile(reviewRoot, "docs"), "f");
copyfile(fullfile(repositoryRoot, "paper_verification_v11", "logs", ...
    "audit_paper_verification_v11.txt"), ...
    fullfile(reviewRoot, "logs"), "f");

reviewReadme = sprintf(strjoin(["# GPT review package\n\n", ...
    "This folder contains the complete final estimator-selection evidence: ", ...
    "the task specification, protocol and locks, ten tables, twelve figures, ", ...
    "the consolidated trace, synchronized reports/metrics, the new audit, ", ...
    "and the parent Paper Verification v1.1 checksum audit.\n\n", ...
    "Review order: `FINAL_ESTIMATOR_DECISION.md`, ", ...
    "`PAPER_METHOD_COMPARISON.md`, tables, figures, then the audit logs.\n"], ""));
fid = fopen(fullfile(reviewRoot, "README_GPT_REVIEW.md"), "w");
assert(fid >= 0, "algsel:ReviewReadme", "Cannot write review README.");
cleaner = onCleanup(@() fclose(fid));
fprintf(fid, "%s", reviewReadme);
end
