% Audit Paper Algorithm Selection v1 evidence and traceability.
scriptDirAudit = string(fileparts(mfilename("fullpath")));
packageRootAudit = string(fileparts(scriptDirAudit));
repositoryRootAudit = string(fileparts(packageRootAudit));
tablesDirAudit = fullfile(packageRootAudit, "results", "tables");
figuresDirAudit = fullfile(packageRootAudit, "results", "figures");
rawDirAudit = fullfile(packageRootAudit, "results", "raw");

staticAudit = readtable(fullfile(tablesDirAudit, ...
    "table_algorithm_static_comparison.csv"), "TextType", "string");
abruptAudit = readtable(fullfile(tablesDirAudit, ...
    "table_algorithm_abrupt_step.csv"), "TextType", "string");
rampAudit = readtable(fullfile(tablesDirAudit, ...
    "table_algorithm_ramp_tracking.csv"), "TextType", "string");
thresholdAudit = readtable(fullfile(tablesDirAudit, ...
    "table_algorithm_threshold_detection.csv"), "TextType", "string");
transientAudit = readtable(fullfile(tablesDirAudit, ...
    "table_algorithm_operating_transients.csv"), "TextType", "string");
noiseAudit = readtable(fullfile(tablesDirAudit, ...
    "table_algorithm_noise_timing.csv"), "TextType", "string");
complexityAudit = readtable(fullfile(tablesDirAudit, ...
    "table_algorithm_complexity.csv"), "TextType", "string");
uncertaintyAudit = readtable(fullfile(tablesDirAudit, ...
    "table_algorithm_uncertainty.csv"), "TextType", "string");
bootstrapAudit = readtable(fullfile(tablesDirAudit, ...
    "table_algorithm_paired_bootstrap.csv"), "TextType", "string");
selectionAudit = readtable(fullfile(tablesDirAudit, ...
    "table_algorithm_final_selection.csv"), "TextType", "string");
traceAudit = readtable(fullfile(rawDirAudit, ...
    "algorithm_selection_consolidated_trace.csv"), "TextType", "string");
lockAudit = readtable(fullfile(packageRootAudit, ...
    "LOCKED_ALGORITHM_SELECTION_HYPERPARAMETERS.csv"), ...
    "TextType", "string");

methodsAudit = ["M1 TS-D-RLS", "M2 TS-SLTVKE", "M3 Dual EKF"];
modesAudit = ["Native", "Equal-Report"];
assert(height(staticAudit) == 6 && all(ismember(methodsAudit, ...
    staticAudit.method)) && all(ismember(modesAudit, staticAudit.mode)), ...
    "algsel:AuditStatic", "Static method/mode matrix is incomplete.");
assert(all(staticAudit.case_count == 768), "algsel:AuditCases", ...
    "Static blind case counts do not preserve 48 x 4 x 4 pairing.");
assert(height(abruptAudit) == 18 && ...
    numel(unique(abruptAudit.case_id)) == 3, "algsel:AuditAbrupt", ...
    "Abrupt C/ESR/joint method/mode matrix is incomplete.");
assert(height(rampAudit) == 162, "algsel:AuditRampRows", ...
    "Expected 162 ramp rows including switching cross-checks.");
mainRampAudit = rampAudit(rampAudit.source_model == ...
    "TRACE_DERIVED_OBSERVATION", :);
assert(height(mainRampAudit) == 144 && ...
    all(ismember([0.1, 1, 10, 100], ...
    unique(mainRampAudit.trajectory_duration_s).')), ...
    "algsel:AuditRampMatrix", "Long-ramp matrix is incomplete.");
assert(height(thresholdAudit) == 360, "algsel:AuditThreshold", ...
    "Threshold-detection matrix is incomplete.");
assert(height(transientAudit) == 24 && ...
    numel(unique(transientAudit.trajectory_type)) == 4, ...
    "algsel:AuditTransient", "Operating-transient matrix is incomplete.");
assert(height(noiseAudit) == 48, "algsel:AuditNoise", ...
    "Noise/timing representative matrix is incomplete.");
assert(height(complexityAudit) == 3 && height(uncertaintyAudit) == 3, ...
    "algsel:AuditAux", "Complexity or uncertainty comparison incomplete.");
assert(height(bootstrapAudit) == 7 && ...
    all(bootstrapAudit.bootstrap_count == 10000), ...
    "algsel:AuditBootstrap", "Paired bootstrap is incomplete.");
assert(lockAudit.rls_lambda(lockAudit.method == "M1 TS-D-RLS") == ...
    0.9975, "algsel:AuditLambda", "RLS lambda was changed.");
tsLockAudit = lockAudit(lockAudit.method == "M2 TS-SLTVKE", :);
dualLockAudit = lockAudit(lockAudit.method == "M3 Dual EKF", :);
assert(tsLockAudit.Q_alpha == 2e-9 && tsLockAudit.Q_ESR == 5e-9 && ...
    tsLockAudit.P0_alpha == 0.0144 && tsLockAudit.P0_R_scale == 0.45 && ...
    tsLockAudit.NIS_gate == 9, "algsel:AuditTsLock", ...
    "TS-SLTVKE frozen Q/P0/gate values changed.");
assert(dualLockAudit.Q_alpha == 2e-10 && dualLockAudit.Q_ESR == 5e-8 && ...
    dualLockAudit.P0_alpha == 0.01 && ...
    dualLockAudit.P0_R_scale == 0.40, "algsel:AuditDualLock", ...
    "Dual EKF frozen Q/P0 values changed.");
frozenShaAudit = ...
    "6B59445898F224C6C070B4E0C3B08E73C7500B5385F912BB058BADBC6AD67225";
assert(all(lockAudit.frozen_algorithm_sha256 == frozenShaAudit), ...
    "algsel:AuditSha", "Frozen algorithm checksum mismatch.");
v11AuditText = fileread(fullfile(repositoryRootAudit, ...
    "paper_verification_v11", "logs", ...
    "audit_paper_verification_v11.txt"));
assert(contains(v11AuditText, "frozen_core_sha256=" + frozenShaAudit), ...
    "algsel:AuditParentSha", "Parent v1.1 checksum is not traceable.");
frozenCorePathAudit = fullfile(repositoryRootAudit, "verification_v21", ...
    "algorithms", "structured_ltv_estimator_v21.m");
assert(sha256FileAudit(frozenCorePathAudit) == frozenShaAudit, ...
    "algsel:AuditFrozenCore", "Frozen TS-SLTVKE source was modified.");
legacyTsAudit = abruptAudit(abruptAudit.method == "M2 TS-SLTVKE" & ...
    ismember(abruptAudit.trajectory_type, ["C_abrupt", "ESR_abrupt"]), :);
assert(height(legacyTsAudit) == 4 && ...
    all(legacyTsAudit.legacy_failure_reproduced), ...
    "algsel:AuditLegacyFailure", ...
    "Frozen TS-SLTVKE 257-cycle failures were not retained.");
assert(all(ismember(["FROZEN_PV11_MODEL_B_ANCHOR", ...
    "TRACE_DERIVED_OBSERVATION", ...
    "FULL_SWITCHING_MODEL_A_EQUATIONS"], unique(traceAudit.source_model))), ...
    "algsel:AuditSourceLabels", "Source-model labels are incomplete.");
assert(all(ismember(["method", "mode", "case_id", "source_model", ...
    "trajectory_type", "trajectory_duration_s", ...
    "health_report_period_s", "noise_profile", "skew_ns", ...
    "C_true", "ESR_true", "C_est", "ESR_est", "C_error", ...
    "ESR_error", "accepted_C_updates", "accepted_R_updates", ...
    "compute_count", "failure_flag", "notes"], ...
    string(traceAudit.Properties.VariableNames))), ...
    "algsel:AuditTraceSchema", "Consolidated trace schema is incomplete.");
assert(numel(unique(selectionAudit.final_decision)) == 1, ...
    "algsel:AuditDecision", "Final decision is not unique.");
decisionAudit = selectionAudit.final_decision(1);
allowedAudit = ["PRIMARY_TS_D_RLS", "PRIMARY_TS_SLTVKE", ...
    "DUAL_REALIZATION", "ESTIMATOR_SELECTION_UNRESOLVED"];
assert(ismember(decisionAudit, allowedAudit), "algsel:AuditDecisionToken", ...
    "Final decision token is invalid.");
assert(contains(fileread(fullfile(packageRootAudit, ...
    "FINAL_ESTIMATOR_DECISION.md")), decisionAudit) && ...
    all(readtable(fullfile(packageRootAudit, ...
    "result_metrics_algorithm_selection_v1.csv"), ...
    "TextType", "string").final_decision == decisionAudit), ...
    "algsel:AuditReportSync", "Report and CSV decisions are not synchronized.");
methodTextAudit = string(fileread(fullfile(packageRootAudit, ...
    "PAPER_METHOD_COMPARISON.md")));
rlsStaticAudit = staticAudit(staticAudit.method == "M1 TS-D-RLS" & ...
    staticAudit.mode == "Native", :);
legacyCAudit = legacyTsAudit(legacyTsAudit.mode == "Native" & ...
    legacyTsAudit.trajectory_type == "C_abrupt", :);
legacyRAudit = legacyTsAudit(legacyTsAudit.mode == "Native" & ...
    legacyTsAudit.trajectory_type == "ESR_abrupt", :);
assert(contains(methodTextAudit, sprintf("%.4f", ...
    rlsStaticAudit.C_mean_MAPE_percent)) && ...
    contains(methodTextAudit, sprintf("%.4f", ...
    legacyCAudit.legacy_257_cycle_error_percent)) && ...
    contains(methodTextAudit, sprintf("%.4f", ...
    legacyRAudit.legacy_257_cycle_error_percent)), ...
    "algsel:AuditNumericSync", ...
    "Key report numbers do not match their source CSV rows.");

requiredFigureAudit = ["fig_alg_01_static_C_ESR.png", ...
    "fig_alg_02_static_p95.png", "fig_alg_03_C_abrupt_step.png", ...
    "fig_alg_04_ESR_abrupt_step.png", ...
    "fig_alg_05_C_ramp_tracking.png", ...
    "fig_alg_06_ESR_ramp_tracking.png", ...
    "fig_alg_07_joint_ramp_tracking.png", ...
    "fig_alg_08_threshold_detection.png", ...
    "fig_alg_09_load_transient_false_health.png", ...
    "fig_alg_10_noise_timing_comparison.png", ...
    "fig_alg_11_complexity_accuracy_pareto.png", ...
    "fig_alg_12_tracking_robustness_pareto.png"];
figureExistsAudit = arrayfun(@(name) isfile(fullfile( ...
    figuresDirAudit, name)), requiredFigureAudit);
assert(all(figureExistsAudit), "algsel:AuditFigures", ...
    "One or more mandatory figures are missing.");

logTextAudit = sprintf(strjoin(["PAPER ALGORITHM SELECTION V1 AUDIT\n", ...
    "timestamp=%s\nstatic_rows=%d\nabrupt_rows=%d\nramp_rows=%d\n", ...
    "threshold_rows=%d\ntransient_rows=%d\nnoise_timing_rows=%d\n", ...
    "bootstrap_rows=%d\ntrace_rows=%d\nfrozen_core_sha256=%s\n", ...
    "final_decision=%s\nAUDIT=PASS\n"], ""), ...
    string(datetime("now", "Format", "yyyy-MM-dd HH:mm:ss")), ...
    height(staticAudit), height(abruptAudit), height(rampAudit), ...
    height(thresholdAudit), height(transientAudit), height(noiseAudit), ...
    height(bootstrapAudit), height(traceAudit), frozenShaAudit, decisionAudit);
logPathAudit = fullfile(packageRootAudit, "logs", ...
    "audit_paper_algorithm_selection_v1.txt");
fidAudit = fopen(logPathAudit, "w");
assert(fidAudit >= 0, "algsel:AuditLog", "Cannot write audit log.");
fprintf(fidAudit, "%s", logTextAudit);
fclose(fidAudit);
fprintf("%s", logTextAudit);

function hash = sha256FileAudit(path)
fid = fopen(path, "r");
assert(fid >= 0, "algsel:AuditHashRead", ...
    "Cannot read frozen source for hashing.");
cleaner = onCleanup(@() fclose(fid));
bytes = fread(fid, Inf, "*uint8");
engine = java.security.MessageDigest.getInstance("SHA-256");
engine.update(bytes);
hash = upper(string(reshape(dec2hex(typecast(engine.digest(), ...
    "uint8"), 2).', 1, [])));
end
