function audit = validate_v23_outputs(root)
%VALIDATE_V23_OUTPUTS Check mandatory v2.3 artifacts and schemas.

if nargin < 1
    root = fileparts(fileparts(mfilename("fullpath")));
end
tableNames = ["table_f28379d_adc_truth.csv" ...
    "table_f28379d_adc_pinmap.csv" "table_f28379d_exact_timing.csv" ...
    "table_epwm_soc_schedule.csv" "table_full_aperture_geometry.csv" ...
    "table_acqps_settling.csv" "table_c1_commonmode.csv" ...
    "table_afe_cmrr.csv" "table_afe_bandwidth_v23.csv" ...
    "table_reference_clock.csv" "table_errata_compliance.csv" ...
    "table_dma_throughput.csv" "table_compute_budget.csv" ...
    "table_v23_monte_carlo.csv" "result_metrics_v23.csv"];
figureNames = "fig_v23_" + compose("%02d", (1:14)') + [ ...
    "_adc_real_timing.png"; "_full_aperture_edge_window.png"; ...
    "_soc_schedule.png"; "_acqps_vs_settling.png"; ...
    "_edge_points_vs_duty.png"; "_c1_diff_commonmode.png"; ...
    "_cmrr_esr_error.png"; "_afe_bw_native_adc.png"; ...
    "_reference_noise.png"; "_adc_error_budget.png"; ...
    "_compute_timeline.png"; "_monte_carlo_accuracy.png"; ...
    "_ci_coverage.png"; "_final_hardware_window.png"];
docNames = ["F28379D_ADC_DATASHEET_CLOSURE.md" ...
    "F28379D_ADC_PINMAP.md" "F28379D_EPWM_ADC_SCHEDULE.md" ...
    "F28379D_ADC_AFE_INTERFACE.md" "F28379D_SILICON_ERRATA_ADC.md" ...
    "F28379D_COMPUTE_BUDGET.md" "F28379D_V23_DECISION.md" ...
    "RESULT_V23_FOR_CHATGPT.md"];
tableExists = isfile(fullfile(root, "results", "tables", tableNames));
figureExists = isfile(fullfile(root, "results", "figures", figureNames));
docExists = isfile(fullfile(root, docNames));
metrics = local_read_metrics(fullfile(root, "result_metrics_v23.csv"));
decision = string(metrics.value(metrics.metric == "decision"));
cfg = v23_default_config();
audit = struct("status", local_status(all(tableExists) && all(figureExists) && ...
    all(docExists) && ismember(decision, cfg.allowedDecisions)), ...
    "mandatoryTables", numel(tableNames), "mandatoryFigures", numel(figureNames), ...
    "mandatoryDocuments", numel(docNames), "decision", decision, ...
    "missingTables", tableNames(~tableExists), ...
    "missingFigures", figureNames(~figureExists), ...
    "missingDocuments", docNames(~docExists));
end

function T = local_read_metrics(file)
opts = delimitedTextImportOptions(NumVariables=4);
opts.DataLines = [2 Inf];
opts.Delimiter = ",";
opts.VariableNames = ["metric" "value" "unit" "status"];
opts.VariableTypes = ["string" "string" "string" "string"];
T = readtable(file, opts);
end

function s = local_status(tf)
if tf
    s = "PASS";
else
    s = "FAIL";
end
end
