function reproduction = reproduce_kR_calibration()
%REPRODUCE_KR_CALIBRATION Rebuild the archived v2.1 edge-gain calibration.
% This function starts from the archived source models, declared operating
% cases, measurement-chain settings, reference ESR truth, and calibration
% seeds. It does not read the manuscript value as a calibration input.

scriptDir = string(fileparts(mfilename("fullpath")));
closureRoot = string(fileparts(scriptDir));
repoRoot = string(fileparts(closureRoot));
resultDir = fullfile(closureRoot,"results");
figureDir = fullfile(closureRoot,"figures");
logDir = fullfile(closureRoot,"logs");
ensureFolders([resultDir figureDir logDir]);

logPath = fullfile(logDir,"reproduce_kR_calibration.log");
diary(logPath);
diaryCleanup = onCleanup(@() diary("off")); %#ok<NASGU>
fprintf("k_R calibration reproduction started %s\n", ...
    string(datetime("now",Format="yyyy-MM-dd HH:mm:ss")));

v1Root = fullfile(repoRoot,"cuk_cap_health_verification");
v2Root = fullfile(repoRoot,"verification_v2");
v21Root = fullfile(repoRoot,"verification_v21");
addpath(genpath(v1Root),genpath(v2Root),genpath(v21Root));

cacheRoot = fullfile(logDir,"simulink_cache");
ensureFolders(cacheRoot);
Simulink.fileGenControl("set",CacheFolder=cacheRoot, ...
    CodeGenFolder=cacheRoot,createDir=true);
simulinkCleanup = onCleanup(@() Simulink.fileGenControl("reset")); %#ok<NASGU>

caseId = ["KR-CAL-01";"KR-CAL-02";"KR-CAL-03";"KR-CAL-04"];
profile = ["nominal";"high_D";"noisy";"modelB_parasitic_nominal"];
sourceModel = ["MODEL_A_SWITCHED_EQUATION"; ...
    "MODEL_A_SWITCHED_EQUATION"; ...
    "MODEL_A_SWITCHED_EQUATION"; ...
    "MODEL_B_SIMSCAPE_ESL_10nH"];
seed = (11901:11904).';

cfg0 = v21_default_config();
bases = cell(4,1);
params = cell(4,1);
cfgs = repmat({cfg0},4,1);
for k = 1:4
    params{k} = model_parameters();
end
params{2}.D = 0.60;
params{2}.Rload = 7.5;
cfgs{3}.sigmaVmV = 10;
cfgs{3}.sigmaImA = 5;
for k = 1:3
    bases{k} = simulate_switched_equation(params{k}, ...
        struct("duration",0.003,"samplesPerPeriod",400));
end
bases{4} = run_modelB_v21(v21Root,params{4},10e-9,0.003);

rawTable = table();
allRatios = zeros(0,1);
for k = 1:4
    cfg = cfgs{k};
    cfg.seed = seed(k);
    measured = v21_measurement_chain(bases{k},params{k},cfg);
    edges = v2_edge_estimates(measured,params{k},cfg);
    ratio = edges.ESR_raw_Ohm ./ params{k}.ESR;
    accepted = ~isnan(ratio); % Exact archived rule: median(...,"omitnan").
    rejectionReason = strings(height(edges),1);
    rejectionReason(~accepted) = "NAN_OMITTED_BY_MEDIAN";
    timing = compose("fsADC=%.9gHz; phase=%.3g; guard=%.3gus; " + ...
        "window=%.3gus; method=timestamped_linear", ...
        cfg.fsAdcHz,cfg.samplePhase,cfg.edgeGuardUs,cfg.edgeWindowUs);
    noise = compose("sigmaV=%.9gmV; sigmaI=%.9gmA", ...
        cfg.sigmaVmV,cfg.sigmaImA);
    n = height(edges);
    rows = table(repmat(caseId(k),n,1),repmat(sourceModel(k),n,1), ...
        repmat(profile(k),n,1),repmat(params{k}.Vin,n,1), ...
        repmat(params{k}.D,n,1),repmat(params{k}.Rload,n,1), ...
        repmat(noise,n,1),repmat(timing,n,1), ...
        repmat(params{k}.ESR,n,1),edges.y_R_V,edges.i_sum_A,ratio, ...
        accepted,rejectionReason,ones(n,1),repmat(seed(k),n,1), ...
        edges.edge_id,edges.edge_time_s, ...
        VariableNames=["case_id" "source_model" "operating_profile" ...
        "Vin" "D" "load" "noise" "timing" "reference_ESR" ...
        "z_R" "I_Sigma" "raw_calibration_quantity" "accepted" ...
        "rejection_reason" "weight" "seed" "edge_id" "edge_time_s"]);
    rawTable = [rawTable;rows]; %#ok<AGROW>
    allRatios = [allRatios;ratio]; %#ok<AGROW>
    fprintf("%s: %d edge ratios, median %.16g\n", ...
        profile(k),height(edges),median(ratio,"omitnan"));
end

% Exact implementation in verification_v21/covariance/train_v21_covariance.m.
kRReproduced = median(allRatios,"omitnan");
lockedPath = fullfile(v21Root,"results","raw","locked_covariance_v21.mat");
lockedData = load(lockedPath,"locked");
kRArchived = lockedData.locked.edgeGainCorrection;
absoluteErrorVsArchived = abs(kRReproduced-kRArchived);
exactArchivedMatch = absoluteErrorVsArchived <= ...
    max(1e-14,10*eps(kRArchived));

% The historical v1 package (0.982 center) was removed in the v0.4 cleanup;
% the drift check now parses the adopted campaign center from the current
% v2 engine. Restore the v1 folder from git history to re-run the original
% historical comparison.
finalConfigPath = fullfile(repoRoot,"paper_algorithm_selection_v2", ...
    "scripts","paper_algorithm_selection_v2_engine.m");
finalConfigText = fileread(finalConfigPath);
token = regexp(finalConfigText, ...
    'cfg\.kRCalibration\s*=\s*([0-9]+(?:\.[0-9]+)?)', ...
    'tokens','once');
assert(~isempty(token),"kR:FinalConfigParse", ...
    "Could not parse cfg.kRCalibration from the frozen final script.");
kRFinalConfig = str2double(token{1});
kRManuscriptRounded = round(kRReproduced,3);
roundedMatchesFinal = kRManuscriptRounded == round(kRFinalConfig,3);
deltaVsFinal = (kRReproduced-kRFinalConfig)/kRFinalConfig;
approximateEsrScaleImpact = -deltaVsFinal;

if exactArchivedMatch && roundedMatchesFinal
    classification = "REPRODUCED_FINAL_LOCK";
elseif exactArchivedMatch
    classification = "KR_VERSION_DRIFT";
else
    classification = "KR_CALIBRATION_FORMULA_MISMATCH";
end

summaryTable = table(kRReproduced,kRArchived,absoluteErrorVsArchived, ...
    exactArchivedMatch,kRManuscriptRounded,kRFinalConfig, ...
    roundedMatchesFinal,deltaVsFinal,approximateEsrScaleImpact, ...
    height(rawTable),nnz(rawTable.accepted),classification, ...
    VariableNames=["kR_reproduced_full" "kR_archived_v21_full" ...
    "absolute_error_vs_archived" "exact_archived_match" ...
    "kR_reproduced_rounded_3" "kR_final_algorithm_config" ...
    "rounded_matches_final" "delta_vs_final_fraction" ...
    "approx_ESR_scale_impact_fraction" "raw_sample_count" ...
    "accepted_sample_count" "classification"]);

sourceManifest = table( ...
    ["calibration implementation";"reference parameter source"; ...
    "Model-A calibration plant";"Model-B calibration plant"; ...
    "measurement chain";"edge reconstruction";"archived locked output"; ...
    "final algorithm config"], ...
    [fullfile(v21Root,"covariance","train_v21_covariance.m"); ...
    fullfile(v1Root,"model","model_parameters.m"); ...
    fullfile(v1Root,"model","simulate_switched_equation.m"); ...
    fullfile(v21Root,"model","run_modelB_v21.m"); ...
    fullfile(v21Root,"sampling","v21_measurement_chain.m"); ...
    fullfile(v2Root,"timing","v2_edge_estimates.m"); ...
    lockedPath;finalConfigPath], ...
    ["calibrate_edge_gain/training_cases";"p.ESR"; ...
    "simulate_switched_equation";"run_modelB_v21"; ...
    "v21_measurement_chain";"ESR_raw_Ohm,y_R_V,i_sum_A"; ...
    "locked.edgeGainCorrection";"cfg.kRCalibration"], ...
    VariableNames=["role" "source_file" "script_function_or_variable"]);

writetable(rawTable,fullfile(resultDir,"table_kR_calibration_raw.csv"));
writetable(summaryTable, ...
    fullfile(resultDir,"table_kR_calibration_summary.csv"));
writetable(sourceManifest,fullfile(resultDir,"table_kR_source_manifest.csv"));

reproduction = struct("kR_reproduced_full",kRReproduced, ...
    "kR_archived_v21_full",kRArchived, ...
    "kR_reproduced_rounded_3",kRManuscriptRounded, ...
    "kR_final_algorithm_config",kRFinalConfig, ...
    "exact_archived_match",exactArchivedMatch, ...
    "rounded_matches_final",roundedMatchesFinal, ...
    "delta_vs_final_fraction",deltaVsFinal, ...
    "classification",classification, ...
    "reference_type","SIMULATION_REFERENCE_TRUTH", ...
    "aggregation","unweighted median of pooled per-edge ratios", ...
    "rejection","NaN omission only", ...
    "weighting","none");
save(fullfile(resultDir,"kR_calibration_reproduction.mat"), ...
    "reproduction","rawTable","summaryTable","sourceManifest");

oldVisibility = get(groot,"defaultFigureVisible");
visibilityCleanup = onCleanup(@() set(groot,"defaultFigureVisible", ...
    oldVisibility)); %#ok<NASGU>
set(groot,"defaultFigureVisible","off");
fig = figure(Color="w",Position=[100 100 1000 600]);
histogram(rawTable.raw_calibration_quantity(rawTable.accepted),36, ...
    FaceColor=[0.16 0.45 0.70],EdgeColor="none");
hold on;
hMedian = xline(kRReproduced,"k-",LineWidth=2, ...
    DisplayName=compose("v2.1 median %.6f",kRReproduced));
hFinal = xline(kRFinalConfig,"r--",LineWidth=2, ...
    DisplayName=compose("final config %.3f",kRFinalConfig));
grid on;
xlabel("Per-edge calibration ratio");
ylabel("Count");
title("Archived v2.1 k_R commissioning ratios");
subtitle("Four calibration profiles; reference ESR is simulation truth");
legend([hMedian hFinal],Location="northwest");
exportgraphics(fig,fullfile(figureDir, ...
    "fig_kR_calibration_distribution.png"),Resolution=220);
close(fig);

fprintf("Reproduced v2.1 k_R (full precision): %.17g\n",kRReproduced);
fprintf("Archived v2.1 k_R (full precision):   %.17g\n",kRArchived);
fprintf("Reproduced rounded to 3 decimals:     %.3f\n",kRManuscriptRounded);
fprintf("Final algorithm configuration:        %.3f\n",kRFinalConfig);
fprintf("Difference relative to final config:  %+.9f %%\n",100*deltaVsFinal);
fprintf("Classification: %s\n",classification);
end

function ensureFolders(paths)
for path = reshape(string(paths),1,[])
    if ~isfolder(path)
        mkdir(path);
    end
end
end
