function comparison = compare_kR_rerun()
%COMPARE_KR_RERUN Audit the 0.982-to-0.97719802594550731 rerun.

scriptDir = string(fileparts(mfilename("fullpath")));
campaignRoot = string(fileparts(scriptDir));
repoRoot = string(fileparts(campaignRoot));
resultDir = fullfile(campaignRoot,"results");
logDir = fullfile(campaignRoot,"logs");
figureDir = fullfile(campaignRoot,"figures");
ensureFolders([resultDir logDir figureDir]);

logPath = fullfile(logDir,"compare_kR_rerun.log");
diary(logPath);
cleanupDiary = onCleanup(@() diary("off")); %#ok<NASGU>

kROld = 0.982;
kRNew = 0.97719802594550731;
fprintf("k_R rerun comparison started %s\n", ...
    string(datetime("now",Format="yyyy-MM-dd HH:mm:ss")));
fprintf("old k_R=%.17g; new k_R=%.17g\n",kROld,kRNew);

pvOldRoot = fullfile(repoRoot,"paper_verification_v11");
pvNewRoot = fullfile(repoRoot,"paper_verification_v12");
algOldRoot = fullfile(repoRoot,"paper_algorithm_selection_v1");
algNewRoot = fullfile(repoRoot,"paper_algorithm_selection_v2");

pvOldRaw = readtable(fullfile(pvOldRoot,"results","raw", ...
    "factorial_rows.csv"),TextType="string");
pvNewRaw = readtable(fullfile(pvNewRoot,"results","raw", ...
    "factorial_rows.csv"),TextType="string");
pvRawKeys = ["observation" "estimator" "case_id" ...
    "noise_profile" "skew_ns" "seed"];
[pvOldRaw,pvNewRaw] = alignTables(pvOldRaw,pvNewRaw,pvRawKeys,4608);
pvRawDeltaSummary = compareNumericVariables( ...
    pvOldRaw,pvNewRaw,"PV_FACTORIAL_RAW");

pvOld = readtable(fullfile(pvOldRoot,"results","tables", ...
    "table_observation_estimator_factorial.csv"),TextType="string");
pvNew = readtable(fullfile(pvNewRoot,"results","tables", ...
    "table_observation_estimator_factorial.csv"),TextType="string");
[pvOld,pvNew] = alignTables(pvOld,pvNew, ...
    ["observation" "estimator"],6);
pvSummaryDelta = compareNumericVariables(pvOld,pvNew, ...
    "PV_FACTORIAL_SUMMARY");

effectOld = readtable(fullfile(pvOldRoot,"results","tables", ...
    "table_observation_effect_bootstrap.csv"),TextType="string");
effectNew = readtable(fullfile(pvNewRoot,"results","tables", ...
    "table_observation_effect_bootstrap.csv"),TextType="string");
[effectOld,effectNew] = alignTables(effectOld,effectNew, ...
    ["estimator" "metric"],18);
effectDelta = compareNumericVariables(effectOld,effectNew, ...
    "PV_OBSERVATION_BOOTSTRAP");

peOld = readtable(fullfile(pvOldRoot,"results","tables", ...
    "table_physical_PE_lower_bound.csv"),TextType="string");
peNew = readtable(fullfile(pvNewRoot,"results","tables", ...
    "table_physical_PE_lower_bound.csv"),TextType="string");
[peOld,peNew] = alignTables(peOld,peNew,"case_id",45);
peDelta = compareNumericVariables(peOld,peNew,"PV_PE_BOUNDS");

algOld = readtable(fullfile(algOldRoot,"results","tables", ...
    "table_algorithm_final_selection.csv"),TextType="string");
algNew = readtable(fullfile(algNewRoot,"results","tables", ...
    "table_algorithm_final_selection.csv"),TextType="string");
[algOld,algNew] = alignTables(algOld,algNew,"metric",height(algOld));
assert(all(algOld.final_decision == algNew.final_decision), ...
    "krRerun:DecisionChanged","Final decision token changed.");
algorithmMetricDelta = metricLongTable(algOld,algNew);

staticOld = readAlgorithmTable(algOldRoot, ...
    "table_algorithm_static_comparison.csv");
staticNew = readAlgorithmTable(algNewRoot, ...
    "table_algorithm_static_comparison.csv");
[staticOld,staticNew] = alignTables(staticOld,staticNew, ...
    ["method" "mode"],6);

noiseOld = readAlgorithmTable(algOldRoot, ...
    "table_algorithm_noise_timing.csv");
noiseNew = readAlgorithmTable(algNewRoot, ...
    "table_algorithm_noise_timing.csv");
[noiseOld,noiseNew] = alignTables(noiseOld,noiseNew, ...
    ["method" "mode" "noise_profile" "skew_ns"],48);

abruptOld = readAlgorithmTable(algOldRoot, ...
    "table_algorithm_abrupt_step.csv");
abruptNew = readAlgorithmTable(algNewRoot, ...
    "table_algorithm_abrupt_step.csv");
[abruptOld,abruptNew] = alignTables(abruptOld,abruptNew, ...
    ["method" "mode" "case_id"],18);

rampOld = readAlgorithmTable(algOldRoot, ...
    "table_algorithm_ramp_tracking.csv");
rampNew = readAlgorithmTable(algNewRoot, ...
    "table_algorithm_ramp_tracking.csv");
[rampOld,rampNew] = alignTables(rampOld,rampNew, ...
    ["method" "mode" "case_id"],162);

transientOld = readAlgorithmTable(algOldRoot, ...
    "table_algorithm_operating_transients.csv");
transientNew = readAlgorithmTable(algNewRoot, ...
    "table_algorithm_operating_transients.csv");
[transientOld,transientNew] = alignTables(transientOld,transientNew, ...
    ["method" "mode" "case_id"],24);

uncertaintyOld = readAlgorithmTable(algOldRoot, ...
    "table_algorithm_uncertainty.csv");
uncertaintyNew = readAlgorithmTable(algNewRoot, ...
    "table_algorithm_uncertainty.csv");
[uncertaintyOld,uncertaintyNew] = alignTables( ...
    uncertaintyOld,uncertaintyNew,"method",3);

complexityOld = readAlgorithmTable(algOldRoot, ...
    "table_algorithm_complexity.csv");
complexityNew = readAlgorithmTable(algNewRoot, ...
    "table_algorithm_complexity.csv");
[complexityOld,complexityNew] = alignTables( ...
    complexityOld,complexityNew,"method",3);

algorithmTableDelta = [ ...
    compareNumericVariables(staticOld,staticNew,"ALG_STATIC"); ...
    compareNumericVariables(noiseOld,noiseNew,"ALG_NOISE_TIMING"); ...
    compareNumericVariables(abruptOld,abruptNew,"ALG_ABRUPT"); ...
    compareNumericVariables(rampOld,rampNew,"ALG_RAMP"); ...
    compareNumericVariables(transientOld,transientNew,"ALG_TRANSIENT"); ...
    compareNumericVariables(uncertaintyOld,uncertaintyNew, ...
        "ALG_UNCERTAINTY"); ...
    compareNumericVariables(complexityOld,complexityNew, ...
        "ALG_COMPLEXITY")];

manuscriptUpdates = buildManuscriptUpdates(pvOld,pvNew,effectOld, ...
    effectNew,staticOld,staticNew,noiseOld,noiseNew,abruptOld, ...
    abruptNew,rampOld,rampNew,transientOld,transientNew, ...
    uncertaintyOld,uncertaintyNew);

checks = table( ...
    ["PV12_FACTORIAL_ROWS";"PV12_BOOTSTRAP_ROWS"; ...
     "PV12_PE_ROWS";"ALG_V2_STATIC_ROWS";"ALG_V2_RAMP_ROWS"; ...
     "ALG_V2_TRANSIENT_ROWS";"ALG_V2_FINAL_DECISION"; ...
     "PE_NUMERIC_FIELDS_UNCHANGED";"COMPLEXITY_FIELDS_UNCHANGED"], ...
    [height(pvNewRaw);height(effectNew);height(peNew);height(staticNew); ...
     height(rampNew);height(transientNew);1; ...
     sum(peDelta.changed_count);sum(compareNumericVariables( ...
        complexityOld,complexityNew,"ALG_COMPLEXITY").changed_count)], ...
    [4608;18;45;6;162;24;1;0;0], ...
    [true;true;true;true;true;true; ...
     all(algNew.final_decision == "DUAL_REALIZATION"); ...
     sum(peDelta.changed_count)==0; ...
     sum(compareNumericVariables(complexityOld,complexityNew, ...
        "ALG_COMPLEXITY").changed_count)==0], ...
    VariableNames=["check" "observed" "expected" "pass"]);
assert(all(checks.pass),"krRerun:InvariantFailure", ...
    "One or more rerun invariants failed.");

writetable(pvRawDeltaSummary,fullfile(resultDir, ...
    "table_pv_raw_delta_summary.csv"));
writetable([pvSummaryDelta;effectDelta;peDelta],fullfile(resultDir, ...
    "table_pv_summary_deltas.csv"));
writetable(algorithmMetricDelta,fullfile(resultDir, ...
    "table_algorithm_metric_deltas.csv"));
writetable(algorithmTableDelta,fullfile(resultDir, ...
    "table_algorithm_table_delta_summary.csv"));
writetable(manuscriptUpdates,fullfile(resultDir, ...
    "table_manuscript_numeric_updates.csv"));
writetable(checks,fullfile(resultDir,"table_rerun_invariance_checks.csv"));

makeStaticDeltaFigure(staticOld,staticNew,figureDir);

comparison = struct("old_kR",kROld,"new_kR",kRNew, ...
    "pv_raw_delta_summary",pvRawDeltaSummary, ...
    "pv_summary_delta",pvSummaryDelta, ...
    "effect_delta",effectDelta,"pe_delta",peDelta, ...
    "algorithm_metric_delta",algorithmMetricDelta, ...
    "algorithm_table_delta",algorithmTableDelta, ...
    "manuscript_updates",manuscriptUpdates,"checks",checks);
save(fullfile(resultDir,"kR_rerun_comparison.mat"),"comparison");

fprintf("PV raw variables with changes: %d\n", ...
    nnz(pvRawDeltaSummary.changed_count>0));
fprintf("Algorithm result-metric cells with changes: %d/%d\n", ...
    nnz(algorithmMetricDelta.changed),height(algorithmMetricDelta));
fprintf("Manuscript-facing numeric rows: %d\n",height(manuscriptUpdates));
fprintf("Final decision: %s\n",algNew.final_decision(1));
fprintf("AUDIT=PASS\n");
end

function T = readAlgorithmTable(root,name)
T = readtable(fullfile(root,"results","tables",name),TextType="string");
end

function ensureFolders(folders)
for folder = folders
    if ~isfolder(folder)
        mkdir(folder);
    end
end
end

function [oldT,newT] = alignTables(oldT,newT,keys,expectedRows)
keys = string(keys);
assert(height(oldT)==expectedRows && height(newT)==expectedRows, ...
    "krRerun:RowCount","Unexpected table row count.");
oldT = sortrows(oldT,keys);
newT = sortrows(newT,keys);
assert(isequal(oldT(:,keys),newT(:,keys)), ...
    "krRerun:KeyMismatch","Old/new table keys do not align.");
assert(height(unique(oldT(:,keys),"rows"))==expectedRows, ...
    "krRerun:DuplicateKey","Comparison key is not unique.");
end

function out = compareNumericVariables(oldT,newT,dataset)
common = intersect(string(oldT.Properties.VariableNames), ...
    string(newT.Properties.VariableNames),"stable");
isNumeric = arrayfun(@(v) isnumeric(oldT.(v)) || islogical(oldT.(v)),common);
variables = common(isNumeric);
n = numel(variables);
datasetCol = repmat(string(dataset),n,1);
row_count = repmat(height(oldT),n,1);
changed_count = zeros(n,1);
max_abs_delta = zeros(n,1);
mean_abs_delta = zeros(n,1);
for k = 1:n
    a = double(oldT.(variables(k)));
    b = double(newT.(variables(k)));
    same = (a==b) | (isnan(a)&isnan(b)) | ...
        (isinf(a)&isinf(b)&sign(a)==sign(b));
    changed_count(k) = nnz(~same);
    finite = isfinite(a) & isfinite(b);
    d = abs(b(finite)-a(finite));
    if isempty(d)
        max_abs_delta(k) = 0;
        mean_abs_delta(k) = 0;
    else
        max_abs_delta(k) = max(d,[],"omitmissing");
        mean_abs_delta(k) = mean(d,"omitmissing");
    end
end
out = table(datasetCol,variables(:),row_count,changed_count, ...
    max_abs_delta,mean_abs_delta,VariableNames=["dataset" "variable" ...
    "row_count" "changed_count" "max_abs_delta" "mean_abs_delta"]);
end

function out = metricLongTable(oldT,newT)
methods = ["M1_TS_D_RLS" "M2_TS_SLTVKE" "M3_Dual_EKF"];
n = height(oldT)*numel(methods);
metric = strings(n,1);
method = strings(n,1);
old_value = zeros(n,1);
new_value = zeros(n,1);
delta = zeros(n,1);
delta_percent = NaN(n,1);
row = 0;
for i = 1:height(oldT)
    for j = 1:numel(methods)
        row = row+1;
        metric(row) = oldT.metric(i);
        method(row) = methods(j);
        old_value(row) = oldT.(methods(j))(i);
        new_value(row) = newT.(methods(j))(i);
        delta(row) = new_value(row)-old_value(row);
        if old_value(row)~=0 && isfinite(old_value(row)) && ...
                isfinite(new_value(row))
            delta_percent(row) = 100*delta(row)/abs(old_value(row));
        end
    end
end
changed = old_value~=new_value & ...
    ~(isnan(old_value)&isnan(new_value)) & ...
    ~(isinf(old_value)&isinf(new_value)&sign(old_value)==sign(new_value));
out = table(metric,method,old_value,new_value,delta,delta_percent,changed);
end

function updates = buildManuscriptUpdates(pvOld,pvNew,effectOld, ...
        effectNew,staticOld,staticNew,noiseOld,noiseNew,abruptOld, ...
        abruptNew,rampOld,rampNew,transientOld,transientNew, ...
        uncertaintyOld,uncertaintyNew)
rows = repmat(updateTemplate(),0,1);

pvVars = ["C_MAPE_percent" "ESR_MAPE_percent" ...
    "C_p95_percent" "ESR_p95_percent" "mean_convergence_cycles"];
for estimator = ["E1 RLS" "E2 Dual EKF" "E3 LTV/Joseph"]
    oldRow = pvOld(pvOld.observation=="O1 Proposed" & ...
        pvOld.estimator==estimator,:);
    newRow = pvNew(pvNew.observation=="O1 Proposed" & ...
        pvNew.estimator==estimator,:);
    for v = pvVars
        rows(end+1,1) = updateRow("Results/observation factorial", ...
            estimator+" "+v,oldRow.(v),newRow.(v),unitFor(v), ...
            "table_observation_estimator_factorial.csv"); %#ok<AGROW>
    end
end

for estimator = ["E1 RLS" "E2 Dual EKF" "E3 LTV/Joseph"]
    for metric = ["C_MAPE" "ESR_MAPE" "convergence"]
        oldRow = effectOld(effectOld.estimator==estimator & ...
            effectOld.metric==metric,:);
        newRow = effectNew(effectNew.estimator==estimator & ...
            effectNew.metric==metric,:);
        for v = ["mean_paired_effect" "ci95_low" "ci95_high"]
            rows(end+1,1) = updateRow("Results/paired bootstrap", ...
                estimator+" "+metric+" "+v,oldRow.(v),newRow.(v), ...
                unitFor(metric),"table_observation_effect_bootstrap.csv"); %#ok<AGROW>
        end
    end
end

staticVars = ["C_mean_MAPE_percent" "ESR_mean_MAPE_percent" ...
    "C_p95_percent" "ESR_p95_percent" "convergence_cycles_mean"];
for method = ["M1 TS-D-RLS" "M2 TS-SLTVKE" "M3 Dual EKF"]
    oldRow = staticOld(staticOld.method==method & staticOld.mode=="Native",:);
    newRow = staticNew(staticNew.method==method & staticNew.mode=="Native",:);
    for v = staticVars
        rows(end+1,1) = updateRow("Results/static comparison", ...
            method+" "+v,oldRow.(v),newRow.(v),unitFor(v), ...
            "table_algorithm_static_comparison.csv"); %#ok<AGROW>
    end
end

for method = ["M1 TS-D-RLS" "M2 TS-SLTVKE" "M3 Dual EKF"]
    maskOld = noiseOld.method==method & noiseOld.mode=="Native" & ...
        noiseOld.noise_profile=="F28379D_device_realistic" & ...
        noiseOld.skew_ns==50;
    maskNew = noiseNew.method==method & noiseNew.mode=="Native" & ...
        noiseNew.noise_profile=="F28379D_device_realistic" & ...
        noiseNew.skew_ns==50;
    for v = ["C_p95_percent" "ESR_p95_percent"]
        rows(end+1,1) = updateRow("Results/noise timing", ...
            method+" F28379D 50ns "+v,noiseOld.(v)(maskOld), ...
            noiseNew.(v)(maskNew),"percent", ...
            "table_algorithm_noise_timing.csv"); %#ok<AGROW>
    end
end

for trajectory = ["C_abrupt" "ESR_abrupt"]
    maskOld = abruptOld.method=="M2 TS-SLTVKE" & ...
        abruptOld.mode=="Native" & abruptOld.trajectory_type==trajectory;
    maskNew = abruptNew.method=="M2 TS-SLTVKE" & ...
        abruptNew.mode=="Native" & abruptNew.trajectory_type==trajectory;
    rows(end+1,1) = updateRow("Results/abrupt stress", ...
        "TS-SLTVKE "+trajectory+" legacy tail error", ...
        abruptOld.legacy_257_cycle_error_percent(maskOld), ...
        abruptNew.legacy_257_cycle_error_percent(maskNew),"percent", ...
        "table_algorithm_abrupt_step.csv"); %#ok<AGROW>
end

durations = [0.1 1 10 100];
for duration = durations
    for method = ["M1 TS-D-RLS" "M2 TS-SLTVKE"]
        oldRows = mainRampRows(rampOld,method,duration);
        newRows = mainRampRows(rampNew,method,duration);
        oldCombined = mean(mean([oldRows.C_nRMSE oldRows.ESR_nRMSE], ...
            2,"omitmissing"),"omitmissing");
        newCombined = mean(mean([newRows.C_nRMSE newRows.ESR_nRMSE], ...
            2,"omitmissing"),"omitmissing");
        rows(end+1,1) = updateRow("Results/ramp table", ...
            method+" "+string(duration)+"s combined nRMSE", ...
            oldCombined,newCombined,"dimensionless", ...
            "table_algorithm_ramp_tracking.csv"); %#ok<AGROW>
        rows(end+1,1) = updateRow("Results/ramp table", ...
            method+" "+string(duration)+"s normalized lag", ...
            mean(oldRows.normalized_lag_percent,"omitmissing"), ...
            mean(newRows.normalized_lag_percent,"omitmissing"), ...
            "percent","table_algorithm_ramp_tracking.csv"); %#ok<AGROW>
    end
end

for method = ["M1 TS-D-RLS" "M2 TS-SLTVKE"]
    oldRows = transientOld(transientOld.method==method & ...
        transientOld.mode=="Native",:);
    newRows = transientNew(transientNew.method==method & ...
        transientNew.mode=="Native",:);
    for v = ["peak_false_C_percent" "peak_false_ESR_percent"]
        rows(end+1,1) = updateRow("Results/operating transients", ...
            method+" mean "+v,mean(oldRows.(v),"omitmissing"), ...
            mean(newRows.(v),"omitmissing"),"percent", ...
            "table_algorithm_operating_transients.csv"); %#ok<AGROW>
    end
end

for method = ["M1 TS-D-RLS" "M2 TS-SLTVKE" "M3 Dual EKF"]
    oldRow = uncertaintyOld(uncertaintyOld.method==method,:);
    newRow = uncertaintyNew(uncertaintyNew.method==method,:);
    rows(end+1,1) = updateRow("Results/uncertainty", ...
        method+" joint 95 coverage",oldRow.joint_95_coverage_percent, ...
        newRow.joint_95_coverage_percent,"percent", ...
        "table_algorithm_uncertainty.csv"); %#ok<AGROW>
end
updates = struct2table(rows);
updates.changed = updates.old_value~=updates.new_value & ...
    ~(isnan(updates.old_value)&isnan(updates.new_value));
end

function rows = mainRampRows(T,method,duration)
rows = T(T.method==method & T.mode=="Native" & ...
    T.source_model=="TRACE_DERIVED_OBSERVATION" & ...
    T.shape=="linear" & T.trajectory_duration_s==duration,:);
assert(height(rows)==3,"krRerun:RampAggregation", ...
    "Expected three linear health trajectories per method/duration.");
end

function item = updateTemplate()
item = struct("section","","quantity","","old_value",0, ...
    "new_value",0,"delta",0,"unit","","source_table","");
end

function item = updateRow(section,quantity,oldValue,newValue,unit,source)
item = updateTemplate();
item.section = string(section);
item.quantity = string(quantity);
item.old_value = oldValue;
item.new_value = newValue;
item.delta = newValue-oldValue;
item.unit = string(unit);
item.source_table = string(source);
end

function unit = unitFor(name)
name = string(name);
if contains(name,"percent") || contains(name,"MAPE")
    unit = "percent";
elseif contains(name,"convergence")
    unit = "cycles";
else
    unit = "reported unit";
end
end

function makeStaticDeltaFigure(oldT,newT,figureDir)
methods = ["M1 TS-D-RLS" "M2 TS-SLTVKE" "M3 Dual EKF"];
oldValue = zeros(3,1);
newValue = zeros(3,1);
for k = 1:3
    oldValue(k) = oldT.ESR_mean_MAPE_percent( ...
        oldT.method==methods(k) & oldT.mode=="Native");
    newValue(k) = newT.ESR_mean_MAPE_percent( ...
        newT.method==methods(k) & newT.mode=="Native");
end
fig = figure(Visible="off",Color="w",Position=[100 100 940 520]);
b = bar([oldValue newValue]);
b(1).FaceColor = [0.45 0.58 0.78];
b(2).FaceColor = [0.86 0.42 0.32];
set(gca,XTick=1:3,XTickLabel=["TS-D-RLS" "TS-SLTVKE" "Dual EKF"]);
ylabel("Mean ESR MAPE (%)");
title("Static ESR result after reproducible k_R adoption");
legend(["k_R=0.982" "k_R=0.97719802594550731"], ...
    Location="northwest");
grid on;
exportgraphics(fig,fullfile(figureDir, ...
    "fig_kR_rerun_static_ESR_comparison.png"),Resolution=220);
close(fig);
end
