function audit=validate_v2_outputs(v2Root)
%VALIDATE_V2_OUTPUTS Check the required v2 deliverables and key row counts.

if nargin<1, v2Root=fileparts(fileparts(mfilename("fullpath"))); end
tableDir=fullfile(v2Root,"results","tables"); figureDir=fullfile(v2Root,"results","figures");
requiredTables=["table_v1_edge_assignment_diagnostics.csv", ...
    "table_edge_estimator_comparison_v2.csv","table_channel_delay_v2.csv", ...
    "table_jitter_v2.csv","table_edge_window_design_v2.csv", ...
    "table_esl_timing_joint_v2.csv","table_frontend_delay_v2.csv", ...
    "table_adc_phase_sweep_v2.csv","table_absolute_noise_v2.csv", ...
    "table_observability_normalized_v2.csv", ...
    "table_covariance_consistency_v2.csv","table_v2_operating_regression.csv", ...
    "result_metrics_v2.csv"];
for file=requiredTables, assert(isfile(fullfile(tableDir,file)),"Missing table: "+file); end
for k=1:20
    stem=sprintf("fig_v2_%02d_",k);
    assert(~isempty(dir(fullfile(figureDir,stem+"*.png"))),"Missing PNG figure "+k);
    assert(~isempty(dir(fullfile(figureDir,stem+"*.fig"))),"Missing FIG figure "+k);
end
for file=["BASELINE_REPRODUCTION.md","V1_V2_COMPARISON.md", ...
        "RESULT_V2_FOR_CHATGPT.md","result_metrics_v2.csv"]
    assert(isfile(fullfile(v2Root,file)),"Missing top-level output: "+file);
end

expected=struct("table_channel_delay_v2",337,"table_jitter_v2",1200, ...
    "table_edge_window_design_v2",120,"table_esl_timing_joint_v2",90, ...
    "table_frontend_delay_v2",15,"table_adc_phase_sweep_v2",480, ...
    "table_absolute_noise_v2",180,"table_observability_normalized_v2",64, ...
    "table_covariance_consistency_v2",153,"table_v2_operating_regression",75);
names=string(fieldnames(expected));
for name=names'
    T=readtable(fullfile(tableDir,name+".csv"));
    assert(height(T)==expected.(name),"Unexpected row count: "+name);
end

M=readtable(fullfile(v2Root,"result_metrics_v2.csv"));
requiredFields=["algorithm_version","edge_method","pre_projection_C", ...
    "pre_projection_ESR","post_projection_C","post_projection_ESR", ...
    "sample_phase_fraction","common_pwm_offset_ns","voltage_delay_ns", ...
    "i1_delay_ns","i2_delay_ns","jitter_rms_ns","adc_aperture_ns", ...
    "voltage_frontend_fc_Hz","i1_frontend_fc_Hz","i2_frontend_fc_Hz", ...
    "edge_guard_us","edge_window_us","edge_points_per_side","edge_fit_order", ...
    "edge_fit_rmse_V","edge_fit_variance_V2","R_V","R_C","R_R", ...
    "NIS_V","NIS_C","NIS_R","gate_V","gate_C","gate_R", ...
    "rank_Obs_normalized","cond_Obs_normalized","min_sv_Obs_normalized", ...
    "info_min_eig","info_cond"];
missing=requiredFields(~ismember(requiredFields,string(M.Properties.VariableNames)));
assert(isempty(missing),"Missing result_metrics fields: "+join(missing,", "));

R=readtable(fullfile(tableDir,"table_v2_operating_regression.csv"),"TextType","string");
assert(sum(R.status=="PASS")==51,"The blind CCM pass count is not 51.");
assert(sum(R.status=="EXCLUDED_DCM")==24,"The excluded DCM count is not 24.");
B=readtable(fullfile(tableDir,"table_model_b_cross_validation_v2.csv"),"TextType","string");
assert(height(B)==4,"Model B must contain four cross-check rows.");
E=readtable(fullfile(tableDir,"table_esl_timing_joint_v2.csv"),"TextType","string");
fail=E.status=="FAIL";
assert(any(abs(E.pre_projection_C_F(fail)-E.C_est_F(fail))>eps), ...
    "Projection-before diagnostics are not distinguishable in failed ESL rows.");

audit=struct("requiredTables",numel(requiredTables),"pngFigures",20, ...
    "figFigures",20,"metricRows",height(M),"metricFields",width(M), ...
    "ccmPass",51,"dcmExcluded",24,"modelBPass",sum(B.status=="PASS"));
fprintf(['v2 output audit PASS: %d tables, 20 PNG + 20 FIG, %d metric rows/' ...
    '%d fields, 51 CCM pass, %d/4 Model B pass.\n'],numel(requiredTables), ...
    height(M),width(M),audit.modelBPass);
end
