function cfg=v21_default_config()
%V21_DEFAULT_CONFIG Locked measurement-chain and estimator design point.

cfg=struct("fsAdcHz",5e6,"samplePhase",.37,"adcBits",16, ...
    "adcApertureS",10e-9,"voltageFullScaleV",100, ...
    "currentFullScaleA",40,"afeOrder",2,"afeFcVHz",2e6, ...
    "afeFcI1Hz",1e6,"afeFcI2Hz",1e6,"sigmaVmV",1, ...
    "sigmaImA",.5,"voltageDelayNs",0,"i1DelayNs",0, ...
    "i2DelayNs",0,"jitterRmsNs",0,"jitterMode","independent", ...
    "commonPwmOffsetNs",0,"edgeGuardUs",.5,"edgeWindowUs",2, ...
    "chargeGuardUs",.5,"dataPolicy","disjoint", ...
    "estimatorVariant","conditional_structured","Cinit",90e-6, ...
    "ESRinit",40e-3,"useBaseTerminalVoltage",true);
end
