function summary = run_v23_all(v23Root)
%RUN_V23_ALL Execute device-specific F28379D verification v2.3.

if nargin < 1
    v23Root = fileparts(fileparts(mfilename("fullpath")));
end
repoRoot = fileparts(v23Root);
addpath(genpath(fullfile(repoRoot, "cuk_cap_health_verification")), ...
    genpath(fullfile(repoRoot, "verification_v2")), ...
    genpath(fullfile(repoRoot, "verification_v21")), ...
    genpath(v23Root));
% verification_v22 was removed in the v0.4 repository cleanup; v2.3 does not
% call any v22 function or read any v22 data file.
local_create_folders(v23Root);
cfg = v23_default_config();
tableDir = fullfile(v23Root, "results", "tables");
rawDir = fullfile(v23Root, "results", "raw");

[caseTable, bases] = v23_modelb_device_data(v23Root, cfg);
writetable(caseTable, fullfile(tableDir, "table_modelB_device_cases_v23.csv"));
tables = v23_build_closure_tables(v23Root, cfg, caseTable);
[seedTable, mcTable] = v23_device_monte_carlo(caseTable, cfg);
writetable(seedTable, fullfile(rawDir, "monte_carlo_seed_level_v23.csv"));
writetable(mcTable, fullfile(tableDir, "table_v23_monte_carlo.csv"));

[metrics, gates, decision] = local_metrics(cfg, tables, mcTable);
writetable(metrics, fullfile(tableDir, "result_metrics_v23.csv"));
writetable(metrics, fullfile(v23Root, "result_metrics_v23.csv"));
writetable(gates, fullfile(tableDir, "table_v23_gates.csv"));
v23_generate_figures(v23Root, cfg, caseTable, bases, tables, ...
    seedTable, mcTable, gates);

summary = struct("decision", decision, "gatesPass", all(gates.pass), ...
    "p95CPercent", max(mcTable.p95_C_abs_error_percent), ...
    "p95ESRPercent", max(mcTable.p95_ESR_abs_error_percent), ...
    "minimumPassFraction", min(mcTable.pass_fraction), ...
    "caseRows", height(caseTable), "seedRows", height(seedTable));
save(fullfile(rawDir, "v23_all_results.mat"), "summary", "cfg", ...
    "caseTable", "bases", "tables", "seedTable", "mcTable", ...
    "metrics", "gates", "-v7.3");
fprintf("v2.3 complete: %s, worst p95 C %.3f%%, ESR %.3f%%, pass %.1f%%.\n", ...
    decision, summary.p95CPercent, summary.p95ESRPercent, ...
    100 * summary.minimumPassFraction);
end

function local_create_folders(root)
folders = [fullfile(root, "results", "tables"), ...
    fullfile(root, "results", "figures"), ...
    fullfile(root, "results", "raw"), fullfile(root, "logs"), ...
    fullfile(root, "gpt_review_package")];
for folder = folders
    if ~isfolder(folder)
        mkdir(folder);
    end
end
end

function [M, G, decision] = local_metrics(cfg, T, MC)
selectedGeometry = T.geometry(T.geometry.selected, :);
selectedSettling = T.settling(T.settling.sourceResistanceOhm == ...
    cfg.sourceResistanceOhm & T.settling.acquisitionNs == ...
    cfg.acquisitionS * 1e9, :);

gateName = ["A_DATASHEET_CLOSURE"; "B_FULL_APERTURE"; ...
    "C_FOUR_ADC_SYNC"; "D_AFE_SETTLING"; "E_COMMON_MODE"; ...
    "F_ERRATA_SAFE"; "G_REAL_TIME"; "H_DEVICE_ACCURACY"];
pass = [all(T.truth.status == "SOURCE_VERIFIED"); ...
    selectedGeometry.full_aperture_pass && selectedGeometry.pipeline_pass; ...
    height(T.schedule) == cfg.socPerAdcPerCycle && ...
        all(T.schedule.adcs == "ADCA/B/C/D identical"); ...
    selectedSettling.pass; ...
    max(MC.p95_C_abs_error_percent) < cfg.cMapeLimitPercent && ...
        max(MC.p95_ESR_abs_error_percent) < cfg.esrMapeLimitPercent; ...
    all(startsWith(T.errata.status, "PASS") | ...
        startsWith(T.errata.status, "NOT_APPLICABLE")); ...
    T.compute.pass(end) && T.timing.value(end) < 1; ...
    min(MC.pass_fraction) >= cfg.requiredPassFraction];
evidence = ["13 critical parameters have TI primary-source citations"; ...
    sprintf("%.3f us full aperture in %.3f us window", ...
        selectedGeometry.full_aperture_span_us, selectedGeometry.window_us); ...
    "Same ePWM trigger, ADCCLK, ACQPS, resolution and SOC policy on ADCA-D"; ...
    sprintf("Rs=%.0f ohm: required %.1f ns, allocated %.1f ns", ...
        cfg.sourceResistanceOhm, selectedSettling.requiredNs, ...
        selectedSettling.acquisitionNs); ...
    sprintf("worst p95 C %.2f%%, ESR %.2f%% with finite CMRR", ...
        max(MC.p95_C_abs_error_percent), max(MC.p95_ESR_abs_error_percent)); ...
    "Revision C selection plus mode/INT/DMA mitigations closed"; ...
    sprintf("ADC utilization %.2f%% and compute allocation %.1f us/20 us", ...
        100 * T.timing.value(end), T.compute.budgetUs(end)); ...
    sprintf("minimum case pass fraction %.1f%% across 200 seeds", ...
        100 * min(MC.pass_fraction))];
G = table(gateName, pass, evidence);

if all(pass)
    decision = "F28379D_INTERNAL_ADC_CONFIRMED_WITH_AFE_CONSTRAINTS";
elseif pass(1) && pass(3) && sum(pass) >= 6
    decision = "F28379D_INTERNAL_ADC_MARGINAL";
else
    decision = "EXTERNAL_ADC_REQUIRED";
end

metric = ["decision"; "actual_sustainable_samples_per_s"; ...
    "selected_guard_us"; "selected_window_us"; "points_per_side"; ...
    "ACQPS"; "full_aperture_span_us"; "full_aperture_margin_us"; ...
    "EPWMCLK_Hz"; "TBPRD"; "per_ADC_utilization_percent"; "DMA_throughput_MB_s"; ...
    "worst_p95_C_error_percent"; "worst_p95_ESR_error_percent"; ...
    "minimum_case_pass_fraction"; "minimum_C_CI95_coverage"; ...
    "minimum_ESR_CI95_coverage"; "all_gates_pass"];
value = [decision; string(cfg.nativeRateHz); string(cfg.guardUs); ...
    string(cfg.windowUs); string(cfg.pointsPerSide); string(cfg.acqps); ...
    string(selectedGeometry.full_aperture_span_us); ...
    string(selectedGeometry.window_us - selectedGeometry.full_aperture_span_us); ...
    string(cfg.epwmclkHz); string(cfg.tbprd); ...
    string(100 * T.timing.value(end)); string(cfg.dmaBytesPerSecond / 1e6); ...
    string(max(MC.p95_C_abs_error_percent)); ...
    string(max(MC.p95_ESR_abs_error_percent)); ...
    string(min(MC.pass_fraction)); ...
    string(min(MC.mean_C_CI95_covered)); ...
    string(min(MC.mean_ESR_CI95_covered)); string(all(pass))];
unit = ["enum"; "sample/s/module"; "us"; "us"; "count"; ...
    "register"; "us"; "us"; "Hz"; "register"; "percent"; "MB/s"; "percent"; ...
    "percent"; "fraction"; "fraction"; "fraction"; "boolean"];
status = repmat("PASS", numel(metric), 1);
status(end) = string(local_pass_label(all(pass)));
M = table(metric, value, unit, status);
end

function label = local_pass_label(tf)
if tf
    label = "PASS";
else
    label = "FAIL";
end
end
