function summary = run_v22_all(v22Root)
%RUN_V22_ALL Execute the complete native-DSP-ADC feasibility study.

if nargin < 1
    v22Root = fileparts(fileparts(mfilename("fullpath")));
end
repoRoot = fileparts(v22Root);
addpath(genpath(fullfile(repoRoot, "cuk_cap_health_verification")), ...
    genpath(fullfile(repoRoot, "verification_v2")), ...
    genpath(fullfile(repoRoot, "verification_v21")), ...
    genpath(v22Root));
create_folders(v22Root);
cfg = v22_default_config();
tableDir = fullfile(v22Root, "results", "tables");
rawDir = fullfile(v22Root, "results", "raw");

profileTable = build_profile_table(cfg);
writetable(profileTable, fullfile(tableDir, ...
    "table_target_dsp_adc_profile_v22.csv"));
[baselineTable, budgetTable, currentRangeTable, bases] = ...
    v22_modelb_baselines(v22Root, cfg);
geometryTable = v22_sampling_geometry(v22Root, cfg, baselineTable, bases);
codeTable = build_code_utilization(cfg, budgetTable);
writetable(codeTable, fullfile(tableDir, ...
    "table_adc_code_utilization_v22.csv"));
kRTable = build_kr_table(cfg);
writetable(kRTable, fullfile(tableDir, "table_kR_robustness_v22.csv"));

worstSignal = select_worst_signal(cfg, budgetTable, baselineTable, ...
    cfg.architectures(2));
nonidealTable = build_nonideal_table(cfg, worstSignal);
writetable(nonidealTable, fullfile(tableDir, ...
    "table_native_adc_nonideal_v22.csv"));
multicycleTable = build_multicycle_table(cfg, worstSignal);
writetable(multicycleTable, fullfile(tableDir, ...
    "table_multicycle_gain_v22.csv"));
[blindTable, comparisonTable, voltageTable] = build_blind_tables(cfg, ...
    budgetTable, baselineTable, geometryTable, codeTable);
writetable(blindTable, fullfile(tableDir, ...
    "table_health_blind_adc_v22.csv"));
writetable(comparisonTable, fullfile(tableDir, ...
    "table_native_vs_external_v22.csv"));
writetable(voltageTable, fullfile(tableDir, ...
    "table_voltage_architecture_v22.csv"));
metricsTable = build_result_metrics(cfg, comparisonTable, geometryTable, ...
    budgetTable, currentRangeTable);
writetable(metricsTable, fullfile(tableDir, "result_metrics_v22.csv"));
writetable(metricsTable, fullfile(v22Root, "result_metrics_v22.csv"));

v22_generate_figures(v22Root, cfg, budgetTable, codeTable, geometryTable, ...
    voltageTable, nonidealTable, multicycleTable, kRTable, comparisonTable);
summary = struct("targetStatus", cfg.targetStatus, ...
    "profileRows", height(profileTable), "budgetRows", height(budgetTable), ...
    "geometryRows", height(geometryTable), "codeRows", height(codeTable), ...
    "nonidealRows", height(nonidealTable), ...
    "multicycleRows", height(multicycleTable), ...
    "kRRows", height(kRTable), "blindRows", height(blindTable), ...
    "comparisonRows", height(comparisonTable), ...
    "recommendedNativeAccuracyPassFraction", comparisonTable.accuracy_pass_fraction( ...
        comparisonTable.path_id == "native_12_V2"));
save(fullfile(rawDir, "v22_all_results.mat"), "summary", "cfg", ...
    "profileTable", "baselineTable", "budgetTable", "currentRangeTable", ...
    "geometryTable", "codeTable", "kRTable", "nonidealTable", ...
    "multicycleTable", "blindTable", "comparisonTable", "voltageTable", ...
    "metricsTable", "-v7.3");
fprintf("v2.2 pipeline complete: %d blind rows, native V2 accuracy pass %.1f%%.\n", ...
    height(blindTable), 100 * summary.recommendedNativeAccuracyPassFraction);
end

function create_folders(v22Root)
folders = [fullfile(v22Root, "results", "tables"), ...
    fullfile(v22Root, "results", "figures"), ...
    fullfile(v22Root, "results", "raw"), ...
    fullfile(v22Root, "logs"), ...
    fullfile(v22Root, "gpt_review_package")];
for folder = folders
    if ~isfolder(folder)
        mkdir(folder);
    end
end
end

function T = build_profile_table(cfg)
n = numel(cfg.profiles);
rows = cell(n, 24);
for k = 1:n
    p = cfg.profiles(k);
    rows(k, :) = {p.name, p.type, p.partNumber, p.resolutionMode, ...
        p.bits, p.fsHz, p.enob, p.moduleCount, p.singleEndedDifferential, ...
        p.socCount, p.pwmTrigger, p.simultaneousConversion, ...
        p.acquisitionWindow, p.conversionLatency, p.inputReferenceV, ...
        p.inputRangeV, p.inl, p.dnl, p.snrSinad, p.offsetError, ...
        p.gainError, p.referenceRequirement, p.channelSkew, p.dataSource};
end
names = ["profile_name" "profile_type" "DSP_part_number" ...
    "resolution_modes" "nominal_bits" "max_sample_rate_Hz" "ENOB" ...
    "number_of_ADC_modules" "single_ended_differential_capability" ...
    "number_of_SOCs" "PWM_trigger_capability" ...
    "simultaneous_concurrent_conversion" "acquisition_window" ...
    "conversion_latency" "input_reference_V" "ADC_input_range" ...
    "INL" "DNL" "SNR_SINAD" "offset_error" "gain_error" ...
    "reference_requirements" "channel_to_channel_skew" "data_source"];
T = cell2table(rows, VariableNames=names);
end

function T = build_code_utilization(cfg, budget)
n = height(budget) * numel(cfg.profiles) * numel(cfg.architectures);
rows = cell(n, 20);
row = 0;
for a = 1:numel(cfg.architectures)
    arch = cfg.architectures(a);
    for p = 1:numel(cfg.profiles)
        profile = cfg.profiles(p);
        rLsb = (arch.rHighV - arch.rLowV) / (2^profile.bits - 1);
        cLsb = (arch.cHighV - arch.cLowV) / (2^profile.bits - 1);
        rmsNoiseCodes = 2^(profile.bits - profile.enob) / sqrt(12);
        for k = 1:height(budget)
            rCodes = budget.edge_ESR_signal_mV(k) * 1e-3 / rLsb;
            cCodes = budget.charge_C_signal_mV(k) * 1e-3 / cLsb;
            row = row + 1;
            rows(row, :) = {arch.id, arch.name, profile.name, profile.bits, ...
                profile.enob, profile.fsHz, budget.operating_case(k), ...
                budget.C(k), budget.ESR(k), rLsb, cLsb, rCodes, cCodes, ...
                rmsNoiseCodes, risk_label(rCodes), risk_label(cCodes), ...
                arch.rHighV - arch.rLowV, arch.cHighV - arch.cLowV, ...
                budget.vT_baseline_V(k), arch.separateEdgeChannel};
        end
    end
end
names = ["voltage_architecture" "architecture_name" "ADC_mode" ...
    "nominal_bits" "ENOB" "fs_adc_Hz" "operating_case" "C_F" ...
    "ESR_Ohm" "LSB_edge_plant_V" "LSB_C_plant_V" "ESR_edge_codes" ...
    "C_charge_window_codes" "RMS_noise_codes" "ESR_code_risk" ...
    "C_code_risk" "edge_plant_span_V" "C_plant_span_V" ...
    "vT_baseline_V" "separate_edge_channel"];
T = cell2table(rows, VariableNames=names);
end

function label = risk_label(codes)
if codes < 4
    label = "HIGH_RISK_LT4";
elseif codes < 16
    label = "QUANTIZATION_SENSITIVE_4_TO_16";
else
    label = "CANDIDATE_GE16";
end
end

function T = build_kr_table(cfg)
duties = [.3 .4 .55 .65];
loads = ["low_CCM" "nominal" "high"];
loadScale = [.5 1 2];
tolerances = [-.05 -.01 .01 .05];
n = numel(duties) * numel(loads) * numel(cfg.CFactors) * ...
    numel(cfg.ESRFactors) * numel(cfg.architectures) * numel(tolerances);
rows = cell(n, 14);
row = 0;
dynamicScale = [1.5 .5 1.0];
for a = 1:numel(cfg.architectures)
    arch = cfg.architectures(a);
    for D = duties
        for l = 1:numel(loads)
            for cFactor = cfg.CFactors
                for rFactor = cfg.ESRFactors
                    dynamic = dynamicScale(a) * (.008 * (D - .475) / .175 + ...
                        .004 * (loadScale(l) - 1) + .003 * (rFactor - 1) + ...
                        .002 * (cFactor - .9) / .1);
                    for tolerance = tolerances
                        raw = arch.nominalKR * (1 + tolerance + dynamic);
                        onceCal = raw / (arch.nominalKR * (1 + tolerance));
                        row = row + 1;
                        rows(row, :) = {arch.id, D, loads(l), loadScale(l), ...
                            cfg.C0 * cFactor, cfg.ESR0 * rFactor, tolerance, ...
                            arch.highpassHz, arch.lowpassHz, raw, onceCal, ...
                            100 * (raw - 1), 100 * (onceCal - 1), ...
                            abs(onceCal - 1) < .01};
                    end
                end
            end
        end
    end
end
names = ["voltage_architecture" "D" "load" "load_scale" "C_F" ...
    "ESR_Ohm" "AFE_component_tolerance" "AFE_highpass_Hz" ...
    "AFE_lowpass_Hz" "kR_raw" "kR_after_once_calibration" ...
    "raw_deviation_percent" "calibrated_deviation_percent" ...
    "one_time_calibration_within_1_percent"];
T = cell2table(rows, VariableNames=names);
end

function signal = select_worst_signal(cfg, budget, baseline, arch)
[~, idx] = min(normalize01(budget.edge_ESR_signal_mV) + ...
    normalize01(budget.charge_C_signal_mV));
signal = make_signal(cfg, budget(idx, :), baseline, arch);
end

function y = normalize01(x)
span = max(x) - min(x);
y = (x - min(x)) / max(span, eps);
end

function signal = make_signal(cfg, row, baseline, arch)
b = baseline(baseline.operating_case == row.operating_case, :);
cFactor = row.C / cfg.C0;
rFactor = row.ESR / cfg.ESR0;
loadTerm = load_term(row.load);
dynamicScale = [1.5 .5 1.0];
a = find(string({cfg.architectures.id}) == arch.id, 1);
dynamic = dynamicScale(a) * (.008 * (row.D - .475) / .175 + ...
    .004 * loadTerm + .003 * (rFactor - 1) + ...
    .002 * (cFactor - .9) / .1);
signal = struct("C", row.C, "ESR", row.ESR, "i1", row.i1, ...
    "i2", row.i2, "I_sum", row.I_sum, "Q", row.Q_safe_C, ...
    "zC", row.charge_C_signal_mV * 1e-3, ...
    "zR", row.edge_ESR_signal_mV * 1e-3, ...
    "vBase", row.vT_baseline_V, ...
    "edgeSlopeVPerS", b.edge_slope_V_per_s, ...
    "kRTrue", arch.nominalKR * (1 + .01 + dynamic));
end

function value = load_term(label)
if label == "low_CCM"
    value = -.5;
elseif label == "high" || label == "high_D"
    value = 1;
else
    value = 0;
end
end

function T = build_nonideal_table(cfg, signal)
arch = cfg.architectures(2);
profile = cfg.profiles(1);
rows = cell(29, 31);
row = 0;
for enob = cfg.enobSweep12
    p = profile;
    p.enob = enob;
    cal = cfg.calibrations(4);
    m = v22_adc_observation_mc(signal, p, arch, cfg.primaryCycles, ...
        "Q3_full_nonideal", cal, cfg.primaryFusion, cfg.mcSeeds, ...
        200000 + row * 100, cfg);
    row = row + 1;
    rows(row, :) = nonideal_row("ENOB_sweep", p, arch, cal, 2, m, cfg);
end
for noise = cfg.analogNoiseSweepmV
    cal = cfg.calibrations(4);
    noiseCase = "Q2_" + string(noise) + "mV";
    m = v22_adc_observation_mc(signal, profile, arch, cfg.primaryCycles, ...
        noiseCase, cal, cfg.primaryFusion, cfg.mcSeeds, ...
        210000 + row * 100, cfg);
    row = row + 1;
    rows(row, :) = nonideal_row("natural_noise_sweep", profile, arch, ...
        cal, noise, m, cfg);
end
for c = 1:numel(cfg.calibrations)
    cal = cfg.calibrations(c);
    m = v22_adc_observation_mc(signal, profile, arch, cfg.primaryCycles, ...
        "Q3_full_nonideal", cal, cfg.primaryFusion, cfg.mcSeeds, ...
        222000, cfg);
    row = row + 1;
    rows(row, :) = nonideal_row("calibration_sweep", profile, arch, ...
        cal, 2, m, cfg);
end
profile16 = cfg.profiles(2);
for c = 1:numel(cfg.calibrations)
    cal = cfg.calibrations(c);
    m = v22_adc_observation_mc(signal, profile16, arch, cfg.primaryCycles, ...
        "Q3_full_nonideal", cal, cfg.primaryFusion, cfg.mcSeeds, ...
        224000, cfg);
    row = row + 1;
    rows(row, :) = nonideal_row("calibration_sweep_native16", profile16, ...
        arch, cal, 2, m, cfg);
end
for level = [0 .5 1 1.5 2]
    pInl = cfg.profiles(1);
    pInl.inlLsb = level;
    pInl.dnlLsb = level / 2;
    cal = cfg.calibrations(4);
    m = v22_adc_observation_mc(signal, pInl, arch, cfg.primaryCycles, ...
        "Q3_full_nonideal", cal, cfg.primaryFusion, cfg.mcSeeds, ...
        226000, cfg);
    row = row + 1;
    rows(row, :) = nonideal_row("INL_DNL_sweep", pInl, arch, cal, 2, m, cfg);
end
for p = 1:numel(cfg.profiles)
    cal = cfg.calibrations(4);
    profile = cfg.profiles(p);
    m = v22_adc_observation_mc(signal, profile, arch, cfg.primaryCycles, ...
        "Q3_full_nonideal", cal, cfg.primaryFusion, cfg.mcSeeds, ...
        230000 + row * 100, cfg);
    row = row + 1;
    rows(row, :) = nonideal_row("mode_full_nonideal", profile, arch, ...
        cal, 2, m, cfg);
end
names = ["sweep_type" "ADC_mode" "voltage_architecture" "nominal_bits" ...
    "ENOB" "fs_adc_Hz" "analog_noise_mV_RMS" "calibration_level" ...
    "quantization_included" "offset_residual_LSB" ...
    "gain_residual_fraction" "INL_peak_LSB" "DNL_peak_LSB" ...
    "reference_noise_LSB_RMS" "channel_skew_residual_ns" ...
    "aperture_jitter_ns_RMS" "acquisition_settling_fraction" ...
    "finite_source_impedance_Ohm" "AFE_group_delay_ns" ...
    "datasheet_status" "C_MAPE_percent" "ESR_MAPE_percent" ...
    "C_bias_percent" "ESR_bias_percent" "NIS_C_mean" "NIS_R_mean" ...
    "NEES_mean" "CI_C_95_coverage" "CI_ESR_95_coverage" ...
    "accuracy_pass" "confidence_pass"];
T = cell2table(rows(1:row, :), VariableNames=names);
end

function values = nonideal_row(type, profile, arch, cal, noise, m, cfg)
values = {type, profile.name, arch.id, profile.bits, profile.enob, ...
    profile.fsHz, noise, cal.name, true, cal.offsetResidualLsb, ...
    cal.gainResidualFraction, profile.inlLsb, profile.dnlLsb, .25, ...
    cal.timingResidualNs, 5, ...
    cal.settlingResidualFraction, 5000, 150, ...
    "DATASHEET_NOT_SPECIFIED_PARAMETER_SWEEP", m.C_MAPE_percent, ...
    m.ESR_MAPE_percent, m.C_bias_percent, m.ESR_bias_percent, ...
    m.NIS_C_mean, m.NIS_R_mean, m.NEES_mean, m.CI_C_95_coverage, ...
    m.CI_ESR_95_coverage, m.accuracy_pass, m.confidence_pass};
if type == "natural_noise_sweep"
    values{12} = 0;
    values{13} = 0;
    values{14} = 0;
    values{16} = 0;
end
if type == "ENOB_sweep"
    values{7} = 2;
end
if profile.type == "native_reference" && cfg.targetStatus == "TARGET_DSP_NOT_FIXED"
    values{20} = "TARGET_DSP_NOT_FIXED_PARAMETER_SWEEP";
end
end

function T = build_multicycle_table(cfg, worstSignal)
paths = path_definitions(cfg);
noiseCases = ["Q1_deterministic" "Q2_2mV" "Q3_full_nonideal"];
fusions = ["TS_SLTVKE_sequential" "weighted_batch_average" ...
    "robust_trimmed_mean"];
n = numel(paths) * numel(cfg.cycles) * numel(noiseCases) * numel(fusions);
rows = cell(n, 27);
row = 0;
for p = 1:numel(paths)
    path = paths(p);
    profile = cfg.profiles(path.profileIndex);
    arch = cfg.architectures(path.archIndex);
    signal = worstSignal;
    signal.kRTrue = arch.nominalKR * (1 + .01);
    for cycleIndex = 1:numel(cfg.cycles)
        nCycle = cfg.cycles(cycleIndex);
        for noiseIndex = 1:numel(noiseCases)
            noiseCase = noiseCases(noiseIndex);
            for fusionIndex = 1:numel(fusions)
                fusion = fusions(fusionIndex);
                cal = cfg.calibrations(4);
                m = v22_adc_observation_mc(signal, profile, arch, nCycle, ...
                    noiseCase, cal, fusion, cfg.mcSeeds, ...
                    300000 + p * 10000 + noiseIndex * 1000 + ...
                    fusionIndex * 100, cfg);
                row = row + 1;
                rows(row, :) = metric_row(path.id, profile, arch, nCycle, ...
                    noiseCase, cal.name, fusion, m);
            end
        end
    end
end
names = metric_names();
T = cell2table(rows, VariableNames=names);
end

function [blind, comparison, voltage] = build_blind_tables(cfg, budget, ...
        baseline, geometry, codeTable)
paths = path_definitions(cfg);
n = numel(paths) * height(budget);
rows = cell(n, 34);
row = 0;
for p = 1:numel(paths)
    path = paths(p);
    profile = cfg.profiles(path.profileIndex);
    arch = cfg.architectures(path.archIndex);
    selected = geometry.selected & geometry.fs_adc_Hz == profile.fsHz;
    geometryPass = any(selected);
    if geometryPass
        g = geometry.guard_us(selected);
        W = geometry.window_us(selected);
        Nw = geometry.points_required_per_side(selected);
    else
        g = NaN;
        W = NaN;
        Nw = NaN;
    end
    for k = 1:height(budget)
        signal = make_signal(cfg, budget(k, :), baseline, arch);
        cal = cfg.calibrations(4);
        m = v22_adc_observation_mc(signal, profile, arch, ...
            cfg.primaryCycles, cfg.primaryNoiseCase, cal, ...
            cfg.primaryFusion, cfg.blindSeeds, 400000 + k * 100, cfg);
        row = row + 1;
        rows(row, :) = {path.id, profile.name, arch.id, profile.bits, ...
            profile.enob, profile.fsHz, budget.operating_case(k), ...
            budget.Vin(k), budget.D(k), budget.load(k), budget.C(k), ...
            budget.ESR(k), budget.I_sum(k), ...
            budget.edge_ESR_signal_mV(k), budget.charge_C_signal_mV(k), ...
            cfg.currentRangeA, cfg.primaryCycles, cfg.primaryCalibration, ...
            g, W, Nw, geometryPass, m.C_est_F, m.ESR_est_Ohm, ...
            m.C_MAPE_percent, m.ESR_MAPE_percent, m.C_bias_percent, ...
            m.ESR_bias_percent, m.NEES_mean, m.CI_C_95_coverage, ...
            m.CI_ESR_95_coverage, m.convergence_cycles, ...
            m.accepted_edge_updates, geometryPass && m.accuracy_pass};
    end
end
names = ["path_id" "ADC_mode" "voltage_architecture" "nominal_bits" ...
    "ENOB" "fs_adc_Hz" "operating_case" "Vin_V" "D" "load" ...
    "C_true_F" "ESR_true_Ohm" "I_sum_A" "edge_ESR_signal_mV" ...
    "charge_C_signal_mV" "current_full_scale_A" "multi_cycle" ...
    "calibration_level" "locked_guard_us" "locked_window_us" ...
    "locked_points_per_side" "sampling_geometry_feasible" "C_est_F" ...
    "ESR_est_Ohm" "C_MAPE_percent" "ESR_MAPE_percent" ...
    "C_bias_percent" "ESR_bias_percent" "NEES" "CI_C_95_coverage" ...
    "CI_ESR_95_coverage" "convergence_cycles" ...
    "accepted_edge_updates" "accuracy_pass"];
blind = cell2table(rows, VariableNames=names);

summaryRows = cell(numel(paths), 20);
for p = 1:numel(paths)
    path = paths(p);
    z = blind(blind.path_id == path.id, :);
    summaryRows(p, :) = {path.id, z.ADC_mode(1), z.voltage_architecture(1), ...
        z.nominal_bits(1), z.ENOB(1), z.fs_adc_Hz(1), cfg.currentRangeA, ...
        cfg.primaryCycles, mean(z.sampling_geometry_feasible), ...
        mean(z.C_MAPE_percent), max(z.C_MAPE_percent), ...
        mean(z.ESR_MAPE_percent), max(z.ESR_MAPE_percent), ...
        mean(z.CI_C_95_coverage), mean(z.CI_ESR_95_coverage), ...
        mean(z.NEES), mean(z.accuracy_pass), ...
        mean(z.CI_C_95_coverage >= .90 & z.CI_ESR_95_coverage >= .90), ...
        mean(z.accuracy_pass) >= .95, path.role};
end
summaryNames = ["path_id" "ADC_mode" "voltage_architecture" ...
    "nominal_bits" "ENOB" "fs_adc_Hz" "current_full_scale_A" ...
    "multi_cycle" "geometry_pass_fraction" "C_MAPE_mean_percent" ...
    "C_MAPE_worst_percent" "ESR_MAPE_mean_percent" ...
    "ESR_MAPE_worst_percent" "CI_C_mean_coverage" ...
    "CI_ESR_mean_coverage" "NEES_mean" "accuracy_pass_fraction" ...
    "confidence_pass_fraction" "meets_95_percent_blind_accuracy" "role"];
comparison = cell2table(summaryRows, VariableNames=summaryNames);

voltageRows = cell(numel(cfg.architectures), 18);
for a = 1:numel(cfg.architectures)
    arch = cfg.architectures(a);
    pathId = "native_12_" + arch.id;
    z = comparison(comparison.path_id == pathId, :);
    codes = codeTable(codeTable.voltage_architecture == arch.id & ...
        codeTable.ADC_mode == "native_12bit_highspeed", :);
    voltageRows(a, :) = {arch.id, arch.name, arch.description, arch.cLowV, ...
        arch.cHighV, arch.rLowV, arch.rHighV, arch.separateEdgeChannel, ...
        arch.highpassHz, arch.lowpassHz, min(codes.ESR_edge_codes), ...
        min(codes.C_charge_window_codes), z.C_MAPE_worst_percent, ...
        z.ESR_MAPE_worst_percent, z.accuracy_pass_fraction, ...
        max(budget.vT_baseline_V) <= arch.cHighV && ...
        min(budget.vT_baseline_V) >= arch.cLowV, ...
        max(budget.edge_ESR_signal_mV) * 1e-3 <= ...
        max(abs([arch.rLowV arch.rHighV])), z.meets_95_percent_blind_accuracy};
end
voltageNames = ["voltage_architecture" "architecture_name" "description" ...
    "C_channel_low_V" "C_channel_high_V" "edge_channel_low_V" ...
    "edge_channel_high_V" "separate_edge_channel" "highpass_Hz" ...
    "lowpass_Hz" "minimum_ESR_codes_12bit" "minimum_C_codes_12bit" ...
    "worst_C_MAPE_percent" "worst_ESR_MAPE_percent" ...
    "blind_accuracy_pass_fraction" "absolute_voltage_no_saturation" ...
    "edge_no_saturation" "result"];
voltage = cell2table(voltageRows, VariableNames=voltageNames);
end

function paths = path_definitions(cfg) %#ok<INUSD>
paths = struct( ...
    "id", {"native_12_V1", "native_12_V2", "native_12_V3", ...
        "native_16_V2", "external_14_V2", "external_16_V2"}, ...
    "profileIndex", {1, 1, 1, 2, 3, 4}, ...
    "archIndex", {1, 2, 3, 2, 2, 2}, ...
    "role", {"Native wide-range", "Native dual-range", ...
        "Native level-shift", "Native high-resolution", ...
        "External 14-bit control", "External 16-bit control"});
end

function values = metric_row(pathId, profile, arch, nCycle, noiseCase, ...
        calibration, fusion, m)
values = {pathId, profile.name, arch.id, profile.bits, profile.enob, ...
    profile.fsHz, nCycle, noiseCase, calibration, fusion, m.C_est_F, ...
    m.ESR_est_Ohm, m.C_MAPE_percent, m.C_MAPE_p95_percent, ...
    m.ESR_MAPE_percent, m.ESR_MAPE_p95_percent, m.C_bias_percent, ...
    m.ESR_bias_percent, m.C_variance, m.ESR_variance, m.NIS_C_mean, ...
    m.NIS_R_mean, m.NEES_mean, m.CI_C_95_coverage, ...
    m.CI_ESR_95_coverage, m.accuracy_pass, m.confidence_pass};
end

function names = metric_names()
names = ["path_id" "ADC_mode" "voltage_architecture" "nominal_bits" ...
    "ENOB" "fs_adc_Hz" "multi_cycle" "quantization_case" ...
    "calibration_level" "fusion_method" "C_est_F" "ESR_est_Ohm" ...
    "C_MAPE_percent" "C_MAPE_p95_percent" "ESR_MAPE_percent" ...
    "ESR_MAPE_p95_percent" "C_bias_percent" "ESR_bias_percent" ...
    "C_variance" "ESR_variance" "NIS_C_mean" "NIS_R_mean" ...
    "NEES_mean" "CI_C_95_coverage" "CI_ESR_95_coverage" ...
    "accuracy_pass" "confidence_pass"];
end

function T = build_result_metrics(cfg, comparison, geometry, budget, currentRange)
n = height(comparison);
rows = cell(n, 18);
for k = 1:n
    z = comparison(k, :);
    rows(k, :) = {"ADC_PATH_" + z.path_id, "native_vs_external", ...
        z.path_id, z.ADC_mode, z.voltage_architecture, z.nominal_bits, ...
        z.ENOB, z.fs_adc_Hz, z.multi_cycle, z.C_MAPE_worst_percent, ...
        z.ESR_MAPE_worst_percent, z.accuracy_pass_fraction, ...
        z.confidence_pass_fraction, z.geometry_pass_fraction, ...
        z.meets_95_percent_blind_accuracy, cfg.targetStatus, ...
        cfg.primaryCalibration, z.role};
end
names = ["test_id" "category" "path_id" "ADC_mode" ...
    "voltage_architecture" "nominal_bits" "ENOB" "fs_adc_Hz" ...
    "multi_cycle" "C_MAPE_worst_percent" "ESR_MAPE_worst_percent" ...
    "blind_accuracy_pass_fraction" "confidence_pass_fraction" ...
    "sampling_geometry_pass_fraction" "status" "target_DSP_status" ...
    "calibration_level" "notes"];
T = cell2table(rows, VariableNames=names);
T.minimum_edge_signal_mV(:) = min(budget.edge_ESR_signal_mV);
T.minimum_charge_signal_mV(:) = min(budget.charge_C_signal_mV);
T.recommended_current_full_scale_A(:) = currentRange.engineering_full_scale_A(2);
T.selected_geometry_count(:) = sum(geometry.selected);
end
