function audit = validate_v22_outputs(v22Root)
%VALIDATE_V22_OUTPUTS Assert all mandatory v2.2 deliverables and gates.

if nargin < 1
    v22Root = fileparts(fileparts(mfilename("fullpath")));
end
tableDir = fullfile(v22Root, "results", "tables");
figureDir = fullfile(v22Root, "results", "figures");
requiredTables = ["table_target_dsp_adc_profile_v22.csv" ...
    "table_health_signal_budget_v22.csv" ...
    "table_current_range_design_v22.csv" ...
    "table_adc_code_utilization_v22.csv" ...
    "table_native_adc_geometry_v22.csv" ...
    "table_native_adc_nonideal_v22.csv" ...
    "table_multicycle_gain_v22.csv" ...
    "table_voltage_architecture_v22.csv" ...
    "table_kR_robustness_v22.csv" ...
    "table_native_vs_external_v22.csv" ...
    "table_health_blind_adc_v22.csv" "result_metrics_v22.csv"];
requiredFigures = ["fig_v22_01_health_signal_amplitude.png" ...
    "fig_v22_02_adc_code_utilization.png" ...
    "fig_v22_03_native_adc_sampling_geometry.png" ...
    "fig_v22_04_voltage_architecture_comparison.png" ...
    "fig_v22_05_esr_error_vs_bits_enob.png" ...
    "fig_v22_06_esr_error_vs_multicycle.png" ...
    "fig_v22_07_C_error_vs_multicycle.png" ...
    "fig_v22_08_deterministic_quantization_floor.png" ...
    "fig_v22_09_calibration_benefit.png" "fig_v22_10_kR_variation.png" ...
    "fig_v22_11_native_vs_external.png" ...
    "fig_v22_12_final_adc_decision_region.png"];
assert(all(isfile(fullfile(tableDir, requiredTables))), ...
    "v22:MissingTable", "A mandatory v2.2 table is missing.");
assert(all(isfile(fullfile(figureDir, requiredFigures))), ...
    "v22:MissingFigure", "A mandatory v2.2 figure is missing.");
assert(all(isfile(fullfile(v22Root, ["TARGET_DSP_ADC_PROFILE.md" ...
    "DSP_ADC_DECISION.md" "RESULT_V22_FOR_CHATGPT.md"]))), ...
    "v22:MissingReport", "A mandatory v2.2 report is missing.");

profile = readtable(fullfile(tableDir, requiredTables(1)), TextType="string");
budget = readtable(fullfile(tableDir, requiredTables(2)), TextType="string");
geometry = readtable(fullfile(tableDir, requiredTables(5)), TextType="string");
nonideal = readtable(fullfile(tableDir, requiredTables(6)), TextType="string");
blind = readtable(fullfile(tableDir, requiredTables(11)), TextType="string");
comparison = readtable(fullfile(tableDir, requiredTables(10)), TextType="string");
assert(all(profile.DSP_part_number == "NOT_FIXED"), "v22:FalseDSPClaim", ...
    "A parameterized profile was presented as a fixed target DSP.");
assert(height(budget) == 36, "v22:BudgetRows", "Expected 36 health budget rows.");
assert(height(geometry) == 960 && sum(geometry.selected) == 8, ...
    "v22:GeometryRows", "Geometry enumeration/selection is incomplete.");
assert(height(nonideal) >= 29, "v22:NonidealRows", ...
    "ADC nonideal sensitivity matrix is incomplete.");
assert(height(blind) == 216, "v22:BlindRows", "Expected 216 blind path rows.");
native16 = comparison(comparison.path_id == "native_16_V2", :);
native12 = comparison(comparison.path_id == "native_12_V2", :);
assert(native16.accuracy_pass_fraction >= .95, "v22:NativeHRFail", ...
    "Native HR reference must pass at least 95%% of blind cases.");
assert(native12.accuracy_pass_fraction < .95, "v22:Native12UnexpectedPass", ...
    "Native 12-bit conclusion changed; re-audit the decision.");
decision = fileread(fullfile(v22Root, "DSP_ADC_DECISION.md"));
assert(contains(decision, "NATIVE_HIGH_RESOLUTION_MODE_REQUIRED"), ...
    "v22:DecisionMismatch", "Forced decision enum is missing.");
audit = struct("status", "PASS", "mandatoryTables", numel(requiredTables), ...
    "mandatoryFigures", numel(requiredFigures), "profileRows", height(profile), ...
    "budgetRows", height(budget), "geometryRows", height(geometry), ...
    "nonidealRows", height(nonideal), "blindRows", height(blind), ...
    "nativeHRAccuracyPassFraction", native16.accuracy_pass_fraction, ...
    "native12AccuracyPassFraction", native12.accuracy_pass_fraction);
fprintf("v2.2 output audit PASS: %d tables, %d figures, %d blind rows.\n", ...
    audit.mandatoryTables, audit.mandatoryFigures, audit.blindRows);
end
